=== Simon-Martens/objekte/examples/musenalm/.editor/collections/agents/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "corporate_body": {
      "type": "boolean"
    },
    "fictional": {
      "type": "boolean"
    },
    "uri": {
      "type": "string"
    },
    "biographical_data": {
      "type": "string"
    },
    "profession": {
      "type": "string"
    },
    "pseudonyms": {
      "type": "string"
    },
    "refs": {
      "type": "string"
    },
    "data": {},
    "created": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "musenalm_id": {
      "type": "number"
    },
    "edit_state": {
      "type": "string"
    },
    "annotation": {
      "type": "string"
    },
    "edit_comment": {
      "type": "string"
    },
    "editor": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "musenalm_id"
  ],
  "additionalProperties": false
}

=== Simon-Martens/objekte/examples/musenalm/data/agents/v131mam5arazl24.json
{
  "annotation": "",
  "biographical_data": "",
  "corporate_body": true,
  "created": "2026-06-11 10:17:36.522Z",
  "data": null,
  "edit_comment": "",
  "edit_state": "Edited",
  "fictional": false,
  "musenalm_id": 3253,
  "name": "Arnold u. Pinther",
  "profession": "",
  "pseudonyms": "",
  "refs": "",
  "updated": "2026-06-11 10:17:36.522Z",
  "uri": "",
  "editor": ""
}

=== Simon-Martens/objekte/examples/musenalm/data/agents/faptm77901k6u4a.json
{
  "annotation": "",
  "biographical_data": "1792-1837",
  "corporate_body": false,
  "created": "2026-06-11 10:17:36.488Z",
  "data": {
    "gnd": {
      "@context": "https://lobid.org/gnd/context.jsonld",
      "biographicalOrHistoricalInformation": [
        "Kupferstecher"
      ],
      "dateOfBirth": [
        "1792"
      ],
      "dateOfDeath": [
        "1837"
      ],
      "depiction": [
        {
          "copyrighted": false,
          "creatorName": [
            "Christian Ernst Stölzel (1792-1837)"
          ],
          "creditText": [
            "Staedel Museum"
          ],
          "id": "https://commons.wikimedia.org/wiki/Special:FilePath/Christian%20Ernst%20St%C3%B6lzel.jpg",
          "license": [
            {
              "abbr": "PD",
              "attributionRequired": false,
              "id": "https://creativecommons.org/publicdomain/mark/1.0/",
              "name": "Public Domain"
            }
          ],
          "publisher": "Wikimedia Commons",
          "thumbnail": "https://commons.wikimedia.org/wiki/Special:FilePath/Christian%20Ernst%20St%C3%B6lzel.jpg?width=270",
          "url": "https://commons.wikimedia.org/wiki/File:Christian%20Ernst%20St%C3%B6lzel.jpg?uselang=de"
        }
      ],
      "deprecatedUri": [
        "https://d-nb.info/gnd/1055548947"
      ],
      "describedBy": {
        "dateModified": "2025-02-05T16:12:22.000",
        "dctCreator": {
          "id": "https://ld.zdb-services.de/resource/organisations/DE-611",
          "label": "https://ld.zdb-services.de/resource/organisations/DE-611"
        },
        "descriptionLevel": {
          "id": "https://d-nb.info/standards/vocab/gnd/description-level#1",
          "label": "Katalogisierungslevel 1"
        },
        "id": "https://d-nb.info/gnd/117265381/about",
        "license": {
          "id": "http://creativecommons.org/publicdomain/zero/1.0/",
          "label": "http://creativecommons.org/publicdomain/zero/1.0/"
        },
        "maintainer": {
          "id": "https://ld.zdb-services.de/resource/organisations/DE-611",
          "label": "https://ld.zdb-services.de/resource/organisations/DE-611"
        }
      },
      "familialRelationship": [
        {
          "id": "https://d-nb.info/gnd/11726539X",
          "label": "Stölzel, Christian Friedrich"
        }
      ],
      "gender": [
        {
          "id": "https://d-nb.info/standards/vocab/gnd/gender#male",
          "label": "Männlich"
        }
      ],
      "geographicAreaCode": [
        {
          "id": "https://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-DE",
          "label": "Deutschland"
        }
      ],
      "gndIdentifier": "117265381",
      "gndSubjectCategory": [
        {
          "id": "https://d-nb.info/standards/vocab/gnd/gnd-sc#13.4p",
          "label": "Personen zu Malerei, Zeichnung, Grafik"
        }
      ],
      "hasParent": [
        {
          "id": "https://d-nb.info/gnd/11726539X",
          "label": "Stölzel, Christian Friedrich"
        }
      ],
      "id": "https://d-nb.info/gnd/117265381",
      "oldAuthorityNumber": [
        "(DE-588a)117265381",
        "(DE-588)1055548947"
      ],
      "preferredName": "Stölzel, Christian Ernst",
      "preferredNameEntityForThePerson": {
        "forename": [
          "Christian Ernst"
        ],
        "surname": [
          "Stölzel"
        ]
      },
      "professionOrOccupation": [
        {
          "id": "https://d-nb.info/gnd/4166165-5",
          "label": "Kupferstecher"
        }
      ],
      "sameAs": [
        {
          "collection": {
            "abbr": "VIAF",
            "icon": "http://viaf.org/viaf/images/viaf.ico",
            "id": "http://www.wikidata.org/entity/Q54919",
            "name": "Virtual International Authority File (VIAF)",
            "publisher": "OCLC"
          },
          "id": "http://viaf.org/viaf/42610749"
        },
        {
          "collection": {
            "abbr": "WIKIDATA",
            "icon": "https://www.wikidata.org/static/favicon/wikidata.ico",
            "id": "http://www.wikidata.org/entity/Q2013",
            "name": "Wikidata",
            "publisher": "Wikimedia Foundation Inc."
          },
          "id": "http://www.wikidata.org/entity/Q47011903"
        },
        {
          "collection": {
            "abbr": "DNB",
            "icon": "http://www.dnb.de/SiteGlobals/StyleBundles/Bilder/favicon.png?__blob=normal&v=1",
            "id": "http://www.wikidata.org/entity/Q36578",
            "name": "Gemeinsame Normdatei (GND) im Katalog der Deutschen Nationalbibliothek",
            "publisher": "Deutsche Nationalbibliothek"
          },
          "id": "https://d-nb.info/gnd/1055548947"
        },
        {
          "collection": {
            "abbr": "DNB",
            "icon": "https://www.dnb.de/SiteGlobals/Frontend/DNBWeb/Images/favicon.png?__blob=normal&v=4",
            "id": "http://www.wikidata.org/entity/Q36578",
            "name": "Gemeinsame Normdatei (GND) im Katalog der Deutschen Nationalbibliothek",
            "publisher": "Deutsche Nationalbibliothek"
          },
          "id": "https://d-nb.info/gnd/117265381/about"
        },
        {
          "collection": {
            "abbr": "dewiki",
            "icon": "https://de.wikipedia.org/static/favicon/wikipedia.ico",
            "id": "http://www.wikidata.org/entity/Q48183",
            "name": "Wikipedia (Deutsch)",
            "publisher": "Wikimedia Foundation Inc."
          },
          "id": "https://de.wikipedia.org/wiki/Christian_Ernst_St%C3%B6lzel"
        },
        {
          "collection": {
            "abbr": "enwiki",
            "icon": "https://en.wikipedia.org/static/favicon/wikipedia.ico",
            "id": "http://www.wikidata.org/entity/Q328",
            "name": "Wikipedia (English)",
            "publisher": "Wikimedia Foundation Inc."
          },
          "id": "https://en.wikipedia.org/wiki/Christian_Ernst_St%C3%B6lzel"
        },
        {
          "collection": {
            "id": "https://isni.org"
          },
          "id": "https://isni.org/isni/0000000066769155"
        },
        {
          "collection": {
            "abbr": "DE-611",
            "icon": "https://kalliope-verbund.info/img/favicon.ico",
            "id": "https://kalliope-verbund.info",
            "name": "Kalliope Verbundkatalog",
            "publisher": "Staatsbibliothek zu Berlin - Preußischer Kulturbesitz"
          },
          "id": "https://kalliope-verbund.info/gnd/117265381"
        },
        {
          "collection": {
            "abbr": "ARCHIV-D",
            "icon": "https://www.archivportal-d.de/favicon.ico",
            "id": "https://www.archivportal-d.de",
            "name": "Archivportal-D",
            "publisher": "Deutsche Digitale Bibliothek"
          },
          "id": "https://www.archivportal-d.de/person/gnd/117265381"
        },
        {
          "collection": {
            "abbr": "DDB",
            "icon": "https://www.deutsche-digitale-bibliothek.de/favicon.ico",
            "id": "http://www.wikidata.org/entity/Q621630",
            "name": "Deutsche Digitale Bibliothek",
            "publisher": "Deutsche Digitale Bibliothek"
          },
          "id": "https://www.deutsche-digitale-bibliothek.de/person/gnd/117265381"
        },
        {
          "collection": {
            "abbr": "Portraitindex",
            "icon": "https://www.portraitindex.de/favicon.ico",
            "id": "https://www.portraitindex.de",
            "name": "Digitaler Portraitindex der druckgraphischen Bildnisse der Frühen Neuzeit",
            "publisher": "Deutsches Dokumentationszentrum für Kunstgeschichte - Bildarchiv Foto Marburg"
          },
          "id": "https://www.portraitindex.de/dokumente/pnd/117265381"
        }
      ],
      "type": [
        "DifferentiatedPerson",
        "Person",
        "AuthorityResource"
      ],
      "variantName": [
        "Stoelzel, Christian Ernst",
        "Stoelzel, Christian E."
      ],
      "variantNameEntityForThePerson": [
        {
          "forename": [
            "Christian Ernst"
          ],
          "surname": [
            "Stoelzel"
          ]
        },
        {
          "forename": [
            "Christian E."
          ],
          "surname": [
            "Stoelzel"
          ]
        }
      ],
      "wikipedia": [
        {
          "id": "https://de.wikipedia.org/wiki/Christian_Ernst_St%C3%B6lzel",
          "label": "https://de.wikipedia.org/wiki/Christian_Ernst_St%C3%B6lzel"
        }
      ]
    },
    "gnd_candidate_count": 1,
    "gnd_match_strategy": "exact_years_preferred_name",
    "gnd_matched_at": "2026-06-11T13:05:09Z",
    "gnd_query_biographical_data": "1792-1837",
    "gnd_query_name": "stölzel, christian ernst"
  },
  "edit_comment": "",
  "edit_state": "Edited",
  "fictional": false,
  "musenalm_id": 2794,
  "name": "Stölzel, Christian Ernst",
  "profession": "Graphik",
  "pseudonyms": "",
  "refs": "T/B XXXII, 88",
  "updated": "2026-06-11 13:29:25.256Z",
  "uri": "https://d-nb.info/gnd/117265381",
  "editor": ""
}

=== Simon-Martens/objekte/examples/musenalm/data/agents/humt8qco29flkds.json
{
  "annotation": "",
  "biographical_data": "",
  "corporate_body": true,
  "created": "2026-06-11 10:17:36.529Z",
  "data": null,
  "edit_comment": "",
  "edit_state": "Edited",
  "fictional": false,
  "musenalm_id": 3374,
  "name": "Chr. Kaiser",
  "profession": "",
  "pseudonyms": "",
  "refs": "",
  "updated": "2026-06-11 10:17:36.529Z",
  "uri": "",
  "editor": ""
}

=== Simon-Martens/objekte/examples/musenalm/data/agents/86olxmkzcg9mqqf.json
{
  "annotation": "",
  "biographical_data": "1776-1852",
  "corporate_body": false,
  "created": "2026-06-11 10:17:36.448Z",
  "data": {
    "gnd": {
      "@context": "https://lobid.org/gnd/context.jsonld",
      "dateOfBirth": [
        "1776"
      ],
      "dateOfDeath": [
        "1852-06-12"
      ],
      "describedBy": {
        "dateModified": "2020-05-08T07:58:50.000",
        "dctCreator": {
          "id": "https://ld.zdb-services.de/resource/organisations/DE-14",
          "label": "https://ld.zdb-services.de/resource/organisations/DE-14"
        },
        "descriptionLevel": {
          "id": "https://d-nb.info/standards/vocab/gnd/description-level#3",
          "label": "Katalogisierungslevel 3"
        },
        "id": "https://d-nb.info/gnd/1017962820/about",
        "license": {
          "id": "http://creativecommons.org/publicdomain/zero/1.0/",
          "label": "http://creativecommons.org/publicdomain/zero/1.0/"
        },
        "maintainer": {
          "id": "https://ld.zdb-services.de/resource/organisations/DE-576",
          "label": "https://ld.zdb-services.de/resource/organisations/DE-576"
        }
      },
      "gender": [
        {
          "id": "https://d-nb.info/standards/vocab/gnd/gender#male",
          "label": "Männlich"
        }
      ],
      "geographicAreaCode": [
        {
          "id": "https://d-nb.info/standards/vocab/gnd/geographic-area-code#ZZ",
          "label": "Land unbekannt"
        }
      ],
      "gndIdentifier": "1017962820",
      "id": "https://d-nb.info/gnd/1017962820",
      "oldAuthorityNumber": [
        "(DE-588a)1017962820"
      ],
      "placeOfBirthAsLiteral": [
        "Liska bei Holič"
      ],
      "placeOfDeath": [
        {
          "id": "https://d-nb.info/gnd/4076310-9",
          "label": "Prag"
        }
      ],
      "preferredName": "Pucherna, Antonin",
      "preferredNameEntityForThePerson": {
        "forename": [
          "Antonin"
        ],
        "surname": [
          "Pucherna"
        ]
      },
      "relatedConferenceOrEvent": [
        {
          "id": "https://d-nb.info/gnd/1054636-4",
          "label": "Consultation Meeting on the Iron and Steel Industry"
        }
      ],
      "sameAs": [
        {
          "collection": {
            "abbr": "VIAF",
            "icon": "http://viaf.org/viaf/images/viaf.ico",
            "id": "http://www.wikidata.org/entity/Q54919",
            "name": "Virtual International Authority File (VIAF)",
            "publisher": "OCLC"
          },
          "id": "http://viaf.org/viaf/83875200"
        },
        {
          "collection": {
            "abbr": "WIKIDATA",
            "icon": "https://www.wikidata.org/static/favicon/wikidata.ico",
            "id": "http://www.wikidata.org/entity/Q2013",
            "name": "Wikidata",
            "publisher": "Wikimedia Foundation Inc."
          },
          "id": "http://www.wikidata.org/entity/Q20851125"
        },
        {
          "collection": {
            "abbr": "DNB",
            "icon": "https://www.dnb.de/SiteGlobals/Frontend/DNBWeb/Images/favicon.png?__blob=normal&v=4",
            "id": "http://www.wikidata.org/entity/Q36578",
            "name": "Gemeinsame Normdatei (GND) im Katalog der Deutschen Nationalbibliothek",
            "publisher": "Deutsche Nationalbibliothek"
          },
          "id": "https://d-nb.info/gnd/1017962820/about"
        },
        {
          "collection": {
            "id": "https://isni.org"
          },
          "id": "https://isni.org/isni/0000000067092115"
        },
        {
          "collection": {
            "abbr": "OEBL",
            "id": "https://www.biographien.ac.at",
            "name": "Österreichisches Biographisches Lexikon",
            "publisher": "Österreichische Akademie der Wissenschaften"
          },
          "id": "https://www.biographien.ac.at/oebl/oebl_P/Pucherna_Antonin_1776_1852.xml?frames=yes"
        }
      ],
      "type": [
        "AuthorityResource",
        "DifferentiatedPerson",
        "Person"
      ]
    },
    "gnd_candidate_count": 1,
    "gnd_match_strategy": "exact_years_preferred_name",
    "gnd_matched_at": "2026-06-11T12:32:42Z",
    "gnd_query_biographical_data": "1776-1852",
    "gnd_query_name": "pucherna, antonin"
  },
  "edit_comment": "",
  "edit_state": "Edited",
  "fictional": false,
  "musenalm_id": 2139,
  "name": "Pucherna, Antonin",
  "profession": "Graphik",
  "pseudonyms": "",
  "refs": "T/B XXVII, 443",
  "updated": "2026-06-11 13:29:24.134Z",
  "uri": "https://d-nb.info/gnd/1017962820",
  "editor": ""
}
