=== Simon-Martens/objekte/examples/musenalm/.editor/collections/series/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1
    },
    "pseudonyms": {
      "type": "string"
    },
    "refs": {
      "type": "string"
    },
    "frequency": {
      "type": "string"
    },
    "created": {
      "type": "string",
      "readOnly": true
    },
    "updated": {
      "type": "string",
      "readOnly": true
    },
    "musenalm_id": {
      "type": "number"
    },
    "edit_state": {
      "type": "string",
      "enum": [
        "Unknown",
        "ToDo",
        "Seen",
        "Partially Edited",
        "Waiting",
        "Review",
        "Edited",
        ""
      ]
    },
    "annotation": {
      "type": "string",
      "x-content": "markdown"
    },
    "edit_comment": {
      "type": "string",
      "x-content": "markdown"
    },
    "editor": {
      "type": "string",
      "description": "Source users ID; that collection was not included in the export.",
      "readOnly": true
    },
    "entries": {
      "type": "array",
      "uniqueItems": true,
      "default": [],
      "x-children": true,
      "items": {
        "type": "string",
        "x-relation": {
          "collection": "entries"
        }
      }
    },
    "related_entries": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "properties": {
          "source_id": {
            "type": "string",
            "minLength": 15,
            "maxLength": 15,
            "pattern": "^[a-z0-9]+$",
            "readOnly": true
          },
          "entry": {
            "type": "string",
            "x-relation": {
              "collection": "entries"
            }
          },
          "annotation": {
            "type": "string",
            "x-content": "markdown"
          },
          "created": {
            "type": "string",
            "readOnly": true
          },
          "updated": {
            "type": "string",
            "readOnly": true
          }
        },
        "required": [
          "entry"
        ],
        "additionalProperties": false,
        "default": {
          "entry": "",
          "annotation": ""
        }
      }
    }
  },
  "required": [
    "title",
    "musenalm_id"
  ],
  "additionalProperties": false
}

=== Simon-Martens/objekte/examples/musenalm/data/series/tx4gs6kn6q9rj7f.json
{
  "annotation": "2 Jgg 1791, 1792\n\nHalle (Dost)\n\nHrsgg: F. S. Mursinna; Faselius",
  "created": "2026-06-11 10:17:36.311Z",
  "edit_comment": "",
  "edit_state": "Edited",
  "frequency": "jährlich",
  "musenalm_id": 2136,
  "pseudonyms": "",
  "refs": "K 107; L/R 175",
  "title": "Taschenbuch, Akademisches",
  "updated": "2026-06-11 10:17:36.311Z",
  "editor": "",
  "entries": [
    "otr7ug7zw3fht62",
    "29dkmcs97neus82"
  ],
  "related_entries": []
}

=== Simon-Martens/objekte/examples/musenalm/data/series/yxuw7dt6y03m6bg.json
{
  "annotation": "3 Jgg 1837–1839 \n\nAschaffenburg (Pergay)",
  "created": "2026-06-11 10:17:36.238Z",
  "edit_comment": "",
  "edit_state": "Edited",
  "frequency": "jährlich",
  "musenalm_id": 1475,
  "pseudonyms": "",
  "refs": "K 39; nicht bei L/R",
  "title": "Cölestina",
  "updated": "2026-06-11 10:17:36.238Z",
  "editor": "",
  "entries": [
    "lotgdn0gpnhi4ka",
    "atz48pfg0uhbsa2",
    "etaohtke8zljz1m"
  ],
  "related_entries": []
}

=== Simon-Martens/objekte/examples/musenalm/data/series/26bhprrt47nctjt.json
{
  "annotation": "Leizig (Sommer)\n\nTA von: Neuestes Taschenbuch für Frauenzimmer edlerer Bildung. Von Eulalia Gutwill. Erster Jahrgang. Mit Kupfern. Leipzig, in der Sommerschen Buchhandlung. 1801 (Alm-1103)",
  "created": "2026-06-11 10:17:36.300Z",
  "edit_comment": "",
  "edit_state": "Edited",
  "frequency": "jährlich",
  "musenalm_id": 2051,
  "pseudonyms": "",
  "refs": "nicht bei K; nicht bei L/R",
  "title": "Taschenbuch für Frauenzimmer edlerer Bildung",
  "updated": "2026-06-11 10:17:36.300Z",
  "editor": "",
  "entries": [
    "0gccbgmhpa9gio8"
  ],
  "related_entries": []
}
