=== Simon-Martens/objekte/examples/musenalm/.editor/collections/contents/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "preferred_title": {
      "type": "string",
      "minLength": 1
    },
    "variant_title": {
      "type": "string"
    },
    "parallel_title": {
      "type": "string"
    },
    "title_statement": {
      "type": "string"
    },
    "subtitle_statement": {
      "type": "string"
    },
    "incipit_statement": {
      "type": "string"
    },
    "responsibility_statement": {
      "type": "string"
    },
    "place_statement": {
      "type": "string"
    },
    "publication_statement": {
      "type": "string"
    },
    "year": {
      "type": "number"
    },
    "pseudonym": {
      "type": "boolean"
    },
    "language": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "abk",
          "aar",
          "afr",
          "aka",
          "alb",
          "amh",
          "ara",
          "arg",
          "arm",
          "asm",
          "ava",
          "ave",
          "aym",
          "aze",
          "bam",
          "bak",
          "baq",
          "bel",
          "ben",
          "bis",
          "bos",
          "bre",
          "bul",
          "bur",
          "cat",
          "cha",
          "che",
          "nya",
          "chi",
          "chu",
          "chv",
          "cor",
          "cos",
          "cre",
          "hrv",
          "cze",
          "dan",
          "div",
          "dut",
          "dzo",
          "eng",
          "epo",
          "est",
          "ewe",
          "fao",
          "fij",
          "fin",
          "fre",
          "fry",
          "ful",
          "gla",
          "glg",
          "lug",
          "geo",
          "ger",
          "gre",
          "kal",
          "grn",
          "guj",
          "hat",
          "hau",
          "heb",
          "her",
          "hin",
          "hmo",
          "hun",
          "ice",
          "ido",
          "ibo",
          "ind",
          "ina",
          "ile",
          "iku",
          "ipk",
          "gle",
          "ita",
          "jpn",
          "jav",
          "kan",
          "kau",
          "kas",
          "kaz",
          "khm",
          "kik",
          "kin",
          "kir",
          "kom",
          "kon",
          "kor",
          "kua",
          "kur",
          "lao",
          "lat",
          "lav",
          "lim",
          "lin",
          "lit",
          "lub",
          "ltz",
          "mac",
          "mlg",
          "may",
          "mal",
          "mlt",
          "glv",
          "mao",
          "mar",
          "mah",
          "mon",
          "nau",
          "nav",
          "nde",
          "nbl",
          "ndo",
          "nep",
          "nor",
          "nob",
          "nno",
          "oci",
          "oji",
          "ori",
          "orm",
          "oss",
          "pli",
          "pus",
          "per",
          "pol",
          "por",
          "pan",
          "que",
          "rum",
          "roh",
          "run",
          "rus",
          "sme",
          "smo",
          "sag",
          "san",
          "srd",
          "srp",
          "sna",
          "snd",
          "sin",
          "slo",
          "slv",
          "som",
          "sot",
          "spa",
          "sun",
          "swa",
          "ssw",
          "swe",
          "tgl",
          "tah",
          "tgk",
          "tam",
          "tat",
          "tel",
          "tha",
          "tib",
          "tir",
          "ton",
          "tso",
          "tsn",
          "tur",
          "tuk",
          "twi",
          "uig",
          "ukr",
          "urd",
          "uzb",
          "ven",
          "vie",
          "vol",
          "wln",
          "wel",
          "wol",
          "xho",
          "iii",
          "yid",
          "yor",
          "zha",
          "zul",
          ""
        ]
      },
      "maxItems": 183,
      "uniqueItems": true
    },
    "content_type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "kartografisches Daten-Set",
          "kartografisches Bild",
          "kartografisches Bewegtbild",
          "kartografisches taktiles Bild",
          "kartografische taktile dreidimensionale Form",
          "kartografische dreidimensionale Form",
          "Computerdaten",
          "Computerprogramm",
          "Bewegungsnotation",
          "Noten",
          "aufgeführte Musik",
          "Geräusche",
          "gesprochenes Wort",
          "unbewegtes Bild",
          "taktiles Bild",
          "taktile Noten",
          "taktile Bewegungsnotation",
          "taktiler Text",
          "taktile dreidimensionale Form",
          "Text",
          "dreidimensionale Form",
          "dreidimensionales Bewegtbild",
          "zweidimensionales Bewegtbild",
          "aufgeführte Bewegung",
          ""
        ]
      },
      "maxItems": 24,
      "uniqueItems": true
    },
    "extent": {
      "type": "string"
    },
    "dimensions": {
      "type": "string"
    },
    "musenalm_type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Corrigenda",
          "Diagramm",
          "Gedicht/Lied",
          "Graphik",
          "Graphik-Verzeichnis",
          "graph. Anleitung",
          "graph. Strickanleitung",
          "graph. Tanzanleitung",
          "Inhaltsverzeichnis",
          "Kalendarium",
          "Karte",
          "Musikbeigabe",
          "Musikbeigaben-Verzeichnis",
          "Motto",
          "Prosa",
          "Rätsel",
          "Sammlung",
          "Spiegel",
          "szen. Darstellung",
          "Tabelle",
          "Tafel",
          "Titel",
          "Text",
          "Trinkspruch",
          "Umschlag",
          "Widmung",
          ""
        ]
      },
      "maxItems": 26,
      "uniqueItems": true
    },
    "musenalm_pagination": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "5. Römische Seitenzählung",
          "7. Römische Seitenzählung",
          "1. Arabische Seitenzählung",
          "4. Römische Seitenzählung",
          "Arabische Seitenzählung",
          "Alphabetische Seitenzählung",
          "2. Arabische Seitenzählung",
          "5. Arabische Seitenzählung",
          "6. Arabische Seitenzählung",
          "8. Römische Seitenzählung",
          "",
          "Römische Seitenzählung",
          "Sonstige Seitenzählung",
          "4. Arabische Seitenzählung",
          "7. Arabische Seitenzählung",
          "1. Römische Seitenzählung",
          "2. Römische Seitenzählung",
          "6. Römische Seitenzählung",
          "3. Arabische Seitenzählung",
          "8. Arabische Seitenzählung",
          "3. Römische Seitenzählung"
        ]
      },
      "maxItems": 21,
      "uniqueItems": true
    },
    "scans": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 1000,
      "uniqueItems": true,
      "description": "Original scan filenames. Binary files were not included in the export."
    },
    "numbering": {
      "type": "number"
    },
    "musenalm_id": {
      "type": "number"
    },
    "created": {
      "type": "string",
      "readOnly": true
    },
    "updated": {
      "type": "string",
      "readOnly": true
    },
    "edit_state": {
      "type": "string",
      "enum": [
        "Unknown",
        "ToDo",
        "Seen",
        "Partially Edited",
        "Waiting",
        "Review",
        "Edited",
        ""
      ]
    },
    "annotation": {
      "type": "string",
      "x-content": "markdown"
    },
    "edit_comment": {
      "type": "string",
      "x-content": "markdown"
    },
    "editor": {
      "type": "string",
      "description": "Source users ID; that collection was not included in the export.",
      "readOnly": true
    },
    "agents": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "properties": {
          "source_id": {
            "type": "string",
            "minLength": 15,
            "maxLength": 15,
            "pattern": "^[a-z0-9]+$",
            "readOnly": true
          },
          "agent": {
            "type": "string",
            "x-relation": {
              "collection": "agents"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "Autor:in",
              "Herausgeber:in",
              "Verlag",
              "Druck",
              "Vertrieb",
              "Zeichner:in",
              "Komponist:in",
              "Künstler:in",
              "Übersetzer:in",
              "Redakteur:in",
              "Kartograf:in",
              "Kupferstecher:in",
              "Dargestellt"
            ]
          },
          "conjecture": {
            "type": "boolean"
          },
          "uncertain": {
            "type": "boolean"
          },
          "created": {
            "type": "string",
            "readOnly": true
          },
          "updated": {
            "type": "string",
            "readOnly": true
          },
          "annotation": {
            "type": "string",
            "x-content": "markdown"
          },
          "edit_comment": {
            "type": "string",
            "x-content": "markdown"
          }
        },
        "required": [
          "agent"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "preferred_title",
    "musenalm_id"
  ],
  "additionalProperties": false
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/q97blbbfg3bjo21.json
{
  "annotation": "Sammlung von kleinen Gedichten und prosaischen Aufsätzen, in Stammbücher (Sammlung INr 9657, Obj 65)",
  "content_type": [],
  "created": "2026-06-11 10:17:46.507Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "87",
  "incipit_statement": "Ich liebe dich! / Von deinem Arm umschlungen / Fühl ich unsterblich seyn!",
  "language": [],
  "musenalm_id": 9744,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 152,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Ich liebe dich! / Von deinem Arm umschlungen / Fühl ich unsterblich seyn!…",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "S. Albrecht",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "",
  "updated": "2001-01-26 00:00:00.000Z",
  "variant_title": "",
  "year": 1792,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:57.422Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:57.422Z",
      "agent": "fby2gdha04397wg",
      "source_id": "x25bd0yitu878te"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/uaxizra6py7z8om.json
{
  "annotation": "paginiert 1. /) Détail aus »Le mariage à la mode par Hogarth« INr 73360, Obj 54 s. Textbezug INr 73361, Obj 55",
  "content_type": [],
  "created": "2026-06-11 10:18:20.893Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "116",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 73362,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 56,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "A",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Nach W. Hogarth von Riepenhausen gest.",
  "scans": [
    "alm_159_73362_nrwg34vh60.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "A",
  "updated": "2000-11-30 00:00:00.000Z",
  "variant_title": "",
  "year": 1786,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:00.769Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:00.769Z",
      "agent": "yylanvnf5ct4jbi",
      "source_id": "9cz3hsbf2epk5ky"
    },
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:00.769Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:00.769Z",
      "agent": "s50e2koeoxpuipg",
      "source_id": "vjm6gp23crplgl8"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/vve2okvuu00vm0g.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11 10:17:42.760Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "224",
  "incipit_statement": "Gesang macht munter! Auf, ihr Freunde / Laßt uns singen",
  "language": [],
  "musenalm_id": 4184,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 129,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Aufruf zu Gesang",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Gleim",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Aufruf zu Gesang",
  "updated": "2000-09-26 00:00:00.000Z",
  "variant_title": "",
  "year": 1796,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:56.987Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:56.987Z",
      "agent": "33cr5ecwlcsbopd",
      "source_id": "qfg9zgp6kkx7y4k"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/tnkhmgcwr03exwi.json
{
  "annotation": "Anhang (Sammlung INr 7768, Obj 52)",
  "content_type": [],
  "created": "2026-06-11 10:17:43.620Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "19",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 7779,
  "musenalm_pagination": [
    "2. Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Prosa"
  ],
  "numbering": 63,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Besondere Zahlbenennungen",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Besondere Zahlbenennungen",
  "updated": "2000-12-07 00:00:00.000Z",
  "variant_title": "",
  "year": 1809,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/pnf75tv1kgjegax.json
{
  "annotation": "Drei Stehgreifsepigrammen nach Aufgaben im Pfänderspiele (Sammlung INr 4173, Obj 118)",
  "content_type": [],
  "created": "2026-06-11 10:17:42.947Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "208",
  "incipit_statement": "Drei Elementen war er Hasser: / In Kopf und Herz und Deckelglas dem / Wasser;",
  "language": [],
  "musenalm_id": 4175,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 120,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "2. / Den Alt-Teutschen nach den vier Elemen- / ten zu schildern",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Fridrich",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "2. / Den Alt-Teutschen nach den vier Elemen- / ten zu schildern",
  "updated": "2000-09-26 00:00:00.000Z",
  "variant_title": "",
  "year": 1796,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:57.011Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:57.011Z",
      "agent": "t3zz4r3fvdi80ts",
      "source_id": "cl6konfskhicydc"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/1dorhx4cuwpi3eo.json
{
  "annotation": "separates Kalendarium",
  "content_type": [],
  "created": "2026-06-11 10:18:06.953Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 54292,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Kalendarium"
  ],
  "numbering": 114,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Almanach /auf / das / Jahr Christi / 1827",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Almanach /auf / das / Jahr Christi / 1827",
  "updated": "2008-01-18 00:00:00.000Z",
  "variant_title": "",
  "year": 1827,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/7rh6qsg2j09lu89.json
{
  "annotation": "Illustration zu »Drittes Jahrhundert der Kirchengeschichte« INr 127528, Obj 3 /) nummeriert 42",
  "content_type": [],
  "created": "2026-06-11 10:18:50.283Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "88",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 127534,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 9,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Martyrium S. Laurentii",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Monsorno inv. Weinrauch sc.",
  "scans": [
    "alm_4771_127534_h7i3p6oj9z.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Martyrium S. Laurentii",
  "updated": "2021-01-13 00:00:00.000Z",
  "variant_title": "",
  "year": 1795,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:02.944Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:02.944Z",
      "agent": "h37i7hdd1a10o2d",
      "source_id": "8lzrt3p2a1zo5ke"
    },
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:02.944Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:02.944Z",
      "agent": "nhcnwrqiq042uja",
      "source_id": "fxutfzpkp734fk4"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/yg9damdpgoipjrh.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11 10:18:31.103Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "107",
  "incipit_statement": "In kalter Asche schlief der Götterfunken, / Den gütig Gott gepflanzt in Menschen- / brust;",
  "language": [],
  "musenalm_id": 93837,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 31,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Der Dichter",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Der Dichter",
  "updated": "2009-01-22 00:00:00.000Z",
  "variant_title": "",
  "year": 1825,
  "editor": "",
  "agents": []
}
