=== Simon-Martens/objekte/examples/musenalm/.editor/collections/contents/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "preferred_title": {
      "type": "string",
      "minLength": 1
    },
    "variant_title": {
      "type": "string"
    },
    "parallel_title": {
      "type": "string"
    },
    "title_statement": {
      "type": "string"
    },
    "subtitle_statement": {
      "type": "string"
    },
    "incipit_statement": {
      "type": "string"
    },
    "responsibility_statement": {
      "type": "string"
    },
    "place_statement": {
      "type": "string"
    },
    "publication_statement": {
      "type": "string"
    },
    "year": {
      "type": "number"
    },
    "pseudonym": {
      "type": "boolean"
    },
    "language": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "abk",
          "aar",
          "afr",
          "aka",
          "alb",
          "amh",
          "ara",
          "arg",
          "arm",
          "asm",
          "ava",
          "ave",
          "aym",
          "aze",
          "bam",
          "bak",
          "baq",
          "bel",
          "ben",
          "bis",
          "bos",
          "bre",
          "bul",
          "bur",
          "cat",
          "cha",
          "che",
          "nya",
          "chi",
          "chu",
          "chv",
          "cor",
          "cos",
          "cre",
          "hrv",
          "cze",
          "dan",
          "div",
          "dut",
          "dzo",
          "eng",
          "epo",
          "est",
          "ewe",
          "fao",
          "fij",
          "fin",
          "fre",
          "fry",
          "ful",
          "gla",
          "glg",
          "lug",
          "geo",
          "ger",
          "gre",
          "kal",
          "grn",
          "guj",
          "hat",
          "hau",
          "heb",
          "her",
          "hin",
          "hmo",
          "hun",
          "ice",
          "ido",
          "ibo",
          "ind",
          "ina",
          "ile",
          "iku",
          "ipk",
          "gle",
          "ita",
          "jpn",
          "jav",
          "kan",
          "kau",
          "kas",
          "kaz",
          "khm",
          "kik",
          "kin",
          "kir",
          "kom",
          "kon",
          "kor",
          "kua",
          "kur",
          "lao",
          "lat",
          "lav",
          "lim",
          "lin",
          "lit",
          "lub",
          "ltz",
          "mac",
          "mlg",
          "may",
          "mal",
          "mlt",
          "glv",
          "mao",
          "mar",
          "mah",
          "mon",
          "nau",
          "nav",
          "nde",
          "nbl",
          "ndo",
          "nep",
          "nor",
          "nob",
          "nno",
          "oci",
          "oji",
          "ori",
          "orm",
          "oss",
          "pli",
          "pus",
          "per",
          "pol",
          "por",
          "pan",
          "que",
          "rum",
          "roh",
          "run",
          "rus",
          "sme",
          "smo",
          "sag",
          "san",
          "srd",
          "srp",
          "sna",
          "snd",
          "sin",
          "slo",
          "slv",
          "som",
          "sot",
          "spa",
          "sun",
          "swa",
          "ssw",
          "swe",
          "tgl",
          "tah",
          "tgk",
          "tam",
          "tat",
          "tel",
          "tha",
          "tib",
          "tir",
          "ton",
          "tso",
          "tsn",
          "tur",
          "tuk",
          "twi",
          "uig",
          "ukr",
          "urd",
          "uzb",
          "ven",
          "vie",
          "vol",
          "wln",
          "wel",
          "wol",
          "xho",
          "iii",
          "yid",
          "yor",
          "zha",
          "zul",
          ""
        ]
      },
      "maxItems": 183,
      "uniqueItems": true
    },
    "content_type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "kartografisches Daten-Set",
          "kartografisches Bild",
          "kartografisches Bewegtbild",
          "kartografisches taktiles Bild",
          "kartografische taktile dreidimensionale Form",
          "kartografische dreidimensionale Form",
          "Computerdaten",
          "Computerprogramm",
          "Bewegungsnotation",
          "Noten",
          "aufgeführte Musik",
          "Geräusche",
          "gesprochenes Wort",
          "unbewegtes Bild",
          "taktiles Bild",
          "taktile Noten",
          "taktile Bewegungsnotation",
          "taktiler Text",
          "taktile dreidimensionale Form",
          "Text",
          "dreidimensionale Form",
          "dreidimensionales Bewegtbild",
          "zweidimensionales Bewegtbild",
          "aufgeführte Bewegung",
          ""
        ]
      },
      "maxItems": 24,
      "uniqueItems": true
    },
    "extent": {
      "type": "string"
    },
    "dimensions": {
      "type": "string"
    },
    "musenalm_type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Corrigenda",
          "Diagramm",
          "Gedicht/Lied",
          "Graphik",
          "Graphik-Verzeichnis",
          "graph. Anleitung",
          "graph. Strickanleitung",
          "graph. Tanzanleitung",
          "Inhaltsverzeichnis",
          "Kalendarium",
          "Karte",
          "Musikbeigabe",
          "Musikbeigaben-Verzeichnis",
          "Motto",
          "Prosa",
          "Rätsel",
          "Sammlung",
          "Spiegel",
          "szen. Darstellung",
          "Tabelle",
          "Tafel",
          "Titel",
          "Text",
          "Trinkspruch",
          "Umschlag",
          "Widmung",
          ""
        ]
      },
      "maxItems": 26,
      "uniqueItems": true
    },
    "musenalm_pagination": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "5. Römische Seitenzählung",
          "7. Römische Seitenzählung",
          "1. Arabische Seitenzählung",
          "4. Römische Seitenzählung",
          "Arabische Seitenzählung",
          "Alphabetische Seitenzählung",
          "2. Arabische Seitenzählung",
          "5. Arabische Seitenzählung",
          "6. Arabische Seitenzählung",
          "8. Römische Seitenzählung",
          "",
          "Römische Seitenzählung",
          "Sonstige Seitenzählung",
          "4. Arabische Seitenzählung",
          "7. Arabische Seitenzählung",
          "1. Römische Seitenzählung",
          "2. Römische Seitenzählung",
          "6. Römische Seitenzählung",
          "3. Arabische Seitenzählung",
          "8. Arabische Seitenzählung",
          "3. Römische Seitenzählung"
        ]
      },
      "maxItems": 21,
      "uniqueItems": true
    },
    "scans": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 1000,
      "uniqueItems": true,
      "description": "Original scan filenames. Binary files were not included in the export."
    },
    "numbering": {
      "type": "number"
    },
    "musenalm_id": {
      "type": "number"
    },
    "created": {
      "type": "string",
      "readOnly": true
    },
    "updated": {
      "type": "string",
      "readOnly": true
    },
    "edit_state": {
      "type": "string",
      "enum": [
        "Unknown",
        "ToDo",
        "Seen",
        "Partially Edited",
        "Waiting",
        "Review",
        "Edited",
        ""
      ]
    },
    "annotation": {
      "type": "string",
      "x-content": "markdown"
    },
    "edit_comment": {
      "type": "string",
      "x-content": "markdown"
    },
    "editor": {
      "type": "string",
      "description": "Source users ID; that collection was not included in the export.",
      "readOnly": true
    },
    "agents": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "properties": {
          "source_id": {
            "type": "string",
            "minLength": 15,
            "maxLength": 15,
            "pattern": "^[a-z0-9]+$",
            "readOnly": true
          },
          "agent": {
            "type": "string",
            "x-relation": {
              "collection": "agents"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "Autor:in",
              "Herausgeber:in",
              "Verlag",
              "Druck",
              "Vertrieb",
              "Zeichner:in",
              "Komponist:in",
              "Künstler:in",
              "Übersetzer:in",
              "Redakteur:in",
              "Kartograf:in",
              "Kupferstecher:in",
              "Dargestellt"
            ]
          },
          "conjecture": {
            "type": "boolean"
          },
          "uncertain": {
            "type": "boolean"
          },
          "created": {
            "type": "string",
            "readOnly": true
          },
          "updated": {
            "type": "string",
            "readOnly": true
          },
          "annotation": {
            "type": "string",
            "x-content": "markdown"
          },
          "edit_comment": {
            "type": "string",
            "x-content": "markdown"
          }
        },
        "required": [
          "agent"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "preferred_title",
    "musenalm_id"
  ],
  "additionalProperties": false
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/g9jslbngswyfz89.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11 10:17:50.941Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "207",
  "incipit_statement": "Echo, Echo! in der Buchen Grunde, / Pythia der wilden Bergnatur!",
  "language": [],
  "musenalm_id": 19410,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 43,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Der Widerhall",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "F. Krug v. Nidda",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Der Widerhall",
  "updated": "2001-11-26 00:00:00.000Z",
  "variant_title": "",
  "year": 1815,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:57.931Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:57.931Z",
      "agent": "ynj6s229zp88pv2",
      "source_id": "p53kzhkjs4ghs0y"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/sjx8o30709nhgs8.json
{
  "annotation": "Vermischte Gedichte (Sammlung INr 36820, Obj 75)",
  "content_type": [],
  "created": "2026-06-11 10:17:58.501Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "296",
  "incipit_statement": "Braver Klepper, ohne Falsch und Tücken, / Immer munter, immer nett und glatt,",
  "language": [],
  "musenalm_id": 36830,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 87,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "An mein Reitpferd",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "F. W. A. Schmidt",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "An mein Reitpferd",
  "updated": "2004-03-18 00:00:00.000Z",
  "variant_title": "",
  "year": 1802,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:58.905Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:58.905Z",
      "agent": "crhcmocsovty64w",
      "source_id": "lspsyxnny4du9s3"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/o9rtcaaux0rb8bl.json
{
  "annotation": "Illustration zu »An Fräulein von ** in D**« von J. G. Jacobi INr 43, Obj 22",
  "content_type": [],
  "created": "2026-06-11 10:17:42.866Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "104",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 97,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 24,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Hymen",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "gravé par Texier",
  "scans": [
    "alm_25_97_10g9zbn93p.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Hymen",
  "updated": "2001-06-12 00:00:00.000Z",
  "variant_title": "",
  "year": 1803,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/dtmevprwtv9p75j.json
{
  "annotation": "Grotesken und Naivitäten der Morgenländer, gesammelt aus dem Talmud und einigen alten christlichen Geschichtsschreibern (Sammlung INr 73236, Obj 32)",
  "content_type": [],
  "created": "2026-06-11 10:18:17.994Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "221",
  "incipit_statement": "Es hat der Rabi, des Channa Enkel, gesagt: Wir fuhren einmal in einem Schiff, und sahen einen Vogel, welcher bis an sein Schienbein in dem Wasser stund und sein Kropf reichte bis an das Firnament des Himmels.",
  "language": [],
  "musenalm_id": 73250,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Prosa"
  ],
  "numbering": 46,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Von dem grossen Wundervogel, wel- / cher bey den Rainen Sir, auch Bar / juchne heisst. / (Aus dem Bava bathra Fol. col. 2.)",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Von dem grossen Wundervogel, wel- / cher bey den Rainen Sir, auch Bar / juchne heisst. / (Aus dem Bava bathra Fol. col. 2.)",
  "updated": "2010-01-20 00:00:00.000Z",
  "variant_title": "",
  "year": 1807,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/xz2ounqb1ykv8gy.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11 10:18:52.567Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 130060,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Titel"
  ],
  "numbering": 5,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "THE / ENGLISH FIRESIDE / UPON THE / BANKS OF THE RHINE",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "THE / ENGLISH FIRESIDE / UPON THE / BANKS OF THE RHINE",
  "updated": "2022-05-09 00:00:00.000Z",
  "variant_title": "",
  "year": 0,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/8r81smbjp2f9yjh.json
{
  "annotation": "I. Räthsel (Sammlung INr 78831, Obj 19)",
  "content_type": [],
  "created": "2026-06-11 10:18:22.838Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "37",
  "incipit_statement": "Man kocht's nicht, man kaut's nicht, man / schlingt's nicht, und schmeckt doch vielen gut.",
  "language": [],
  "musenalm_id": 78834,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Rätsel"
  ],
  "numbering": 22,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "3.",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "3.",
  "updated": "2010-02-18 00:00:00.000Z",
  "variant_title": "",
  "year": 1800,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/nmruxfj8iaoi4et.json
{
  "annotation": "Wehmut und Liebe (Sammlung INr 49043, Obj 71)",
  "content_type": [],
  "created": "2026-06-11 10:18:03.151Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "152",
  "incipit_statement": "Laß Andre Vieles seyn, und mehr als du auf Erden; / Hier trachte, ganz du selbst, ein Engel dort zu werden.",
  "language": [],
  "musenalm_id": 49057,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 87,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Sinnspruch",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Friedrich, Baron de la Motte Fouqué",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Sinnspruch",
  "updated": "2007-04-17 00:00:00.000Z",
  "variant_title": "",
  "year": 1812,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:59.482Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:59.482Z",
      "agent": "vwa4f73bcjeod59",
      "source_id": "s7ofj7qo7a0c583"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/gvyotnnffywqhrl.json
{
  "annotation": "Oesterreichische Volkssagen (Sammlung INr 129951, Obj 94)",
  "content_type": [],
  "created": "2026-06-11 10:18:52.025Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "220",
  "incipit_statement": "Als am Landungsplatze zu Fabiana der Verwundete anlangte, ward er mühsam über Schutt und Steine, nach dem, am meisten verheerten Theile der einst so blühenden Stadt getragen,",
  "language": [],
  "musenalm_id": 129955,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Prosa"
  ],
  "numbering": 98,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "4. / Die St. Rupprechtskirche in Wien",
  "pseudonym": true,
  "publication_statement": "",
  "responsibility_statement": "Emil",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "4. / Die St. Rupprechtskirche in Wien",
  "updated": "2022-03-23 00:00:00.000Z",
  "variant_title": "",
  "year": 1835,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:03.027Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:03.027Z",
      "agent": "wzmgymh9fjau9gk",
      "source_id": "nsaugmkea7c8z1q"
    }
  ]
}
