=== Simon-Martens/objekte/examples/musenalm/.editor/collections/contents/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "preferred_title": {
      "type": "string",
      "minLength": 1
    },
    "variant_title": {
      "type": "string"
    },
    "parallel_title": {
      "type": "string"
    },
    "title_statement": {
      "type": "string"
    },
    "subtitle_statement": {
      "type": "string"
    },
    "incipit_statement": {
      "type": "string"
    },
    "responsibility_statement": {
      "type": "string"
    },
    "place_statement": {
      "type": "string"
    },
    "publication_statement": {
      "type": "string"
    },
    "year": {
      "type": "number"
    },
    "pseudonym": {
      "type": "boolean"
    },
    "language": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "abk",
          "aar",
          "afr",
          "aka",
          "alb",
          "amh",
          "ara",
          "arg",
          "arm",
          "asm",
          "ava",
          "ave",
          "aym",
          "aze",
          "bam",
          "bak",
          "baq",
          "bel",
          "ben",
          "bis",
          "bos",
          "bre",
          "bul",
          "bur",
          "cat",
          "cha",
          "che",
          "nya",
          "chi",
          "chu",
          "chv",
          "cor",
          "cos",
          "cre",
          "hrv",
          "cze",
          "dan",
          "div",
          "dut",
          "dzo",
          "eng",
          "epo",
          "est",
          "ewe",
          "fao",
          "fij",
          "fin",
          "fre",
          "fry",
          "ful",
          "gla",
          "glg",
          "lug",
          "geo",
          "ger",
          "gre",
          "kal",
          "grn",
          "guj",
          "hat",
          "hau",
          "heb",
          "her",
          "hin",
          "hmo",
          "hun",
          "ice",
          "ido",
          "ibo",
          "ind",
          "ina",
          "ile",
          "iku",
          "ipk",
          "gle",
          "ita",
          "jpn",
          "jav",
          "kan",
          "kau",
          "kas",
          "kaz",
          "khm",
          "kik",
          "kin",
          "kir",
          "kom",
          "kon",
          "kor",
          "kua",
          "kur",
          "lao",
          "lat",
          "lav",
          "lim",
          "lin",
          "lit",
          "lub",
          "ltz",
          "mac",
          "mlg",
          "may",
          "mal",
          "mlt",
          "glv",
          "mao",
          "mar",
          "mah",
          "mon",
          "nau",
          "nav",
          "nde",
          "nbl",
          "ndo",
          "nep",
          "nor",
          "nob",
          "nno",
          "oci",
          "oji",
          "ori",
          "orm",
          "oss",
          "pli",
          "pus",
          "per",
          "pol",
          "por",
          "pan",
          "que",
          "rum",
          "roh",
          "run",
          "rus",
          "sme",
          "smo",
          "sag",
          "san",
          "srd",
          "srp",
          "sna",
          "snd",
          "sin",
          "slo",
          "slv",
          "som",
          "sot",
          "spa",
          "sun",
          "swa",
          "ssw",
          "swe",
          "tgl",
          "tah",
          "tgk",
          "tam",
          "tat",
          "tel",
          "tha",
          "tib",
          "tir",
          "ton",
          "tso",
          "tsn",
          "tur",
          "tuk",
          "twi",
          "uig",
          "ukr",
          "urd",
          "uzb",
          "ven",
          "vie",
          "vol",
          "wln",
          "wel",
          "wol",
          "xho",
          "iii",
          "yid",
          "yor",
          "zha",
          "zul",
          ""
        ]
      },
      "maxItems": 183,
      "uniqueItems": true
    },
    "content_type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "kartografisches Daten-Set",
          "kartografisches Bild",
          "kartografisches Bewegtbild",
          "kartografisches taktiles Bild",
          "kartografische taktile dreidimensionale Form",
          "kartografische dreidimensionale Form",
          "Computerdaten",
          "Computerprogramm",
          "Bewegungsnotation",
          "Noten",
          "aufgeführte Musik",
          "Geräusche",
          "gesprochenes Wort",
          "unbewegtes Bild",
          "taktiles Bild",
          "taktile Noten",
          "taktile Bewegungsnotation",
          "taktiler Text",
          "taktile dreidimensionale Form",
          "Text",
          "dreidimensionale Form",
          "dreidimensionales Bewegtbild",
          "zweidimensionales Bewegtbild",
          "aufgeführte Bewegung",
          ""
        ]
      },
      "maxItems": 24,
      "uniqueItems": true
    },
    "extent": {
      "type": "string"
    },
    "dimensions": {
      "type": "string"
    },
    "musenalm_type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Corrigenda",
          "Diagramm",
          "Gedicht/Lied",
          "Graphik",
          "Graphik-Verzeichnis",
          "graph. Anleitung",
          "graph. Strickanleitung",
          "graph. Tanzanleitung",
          "Inhaltsverzeichnis",
          "Kalendarium",
          "Karte",
          "Musikbeigabe",
          "Musikbeigaben-Verzeichnis",
          "Motto",
          "Prosa",
          "Rätsel",
          "Sammlung",
          "Spiegel",
          "szen. Darstellung",
          "Tabelle",
          "Tafel",
          "Titel",
          "Text",
          "Trinkspruch",
          "Umschlag",
          "Widmung",
          ""
        ]
      },
      "maxItems": 26,
      "uniqueItems": true
    },
    "musenalm_pagination": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "5. Römische Seitenzählung",
          "7. Römische Seitenzählung",
          "1. Arabische Seitenzählung",
          "4. Römische Seitenzählung",
          "Arabische Seitenzählung",
          "Alphabetische Seitenzählung",
          "2. Arabische Seitenzählung",
          "5. Arabische Seitenzählung",
          "6. Arabische Seitenzählung",
          "8. Römische Seitenzählung",
          "",
          "Römische Seitenzählung",
          "Sonstige Seitenzählung",
          "4. Arabische Seitenzählung",
          "7. Arabische Seitenzählung",
          "1. Römische Seitenzählung",
          "2. Römische Seitenzählung",
          "6. Römische Seitenzählung",
          "3. Arabische Seitenzählung",
          "8. Arabische Seitenzählung",
          "3. Römische Seitenzählung"
        ]
      },
      "maxItems": 21,
      "uniqueItems": true
    },
    "scans": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 1000,
      "uniqueItems": true,
      "description": "Original scan filenames. Binary files were not included in the export."
    },
    "numbering": {
      "type": "number"
    },
    "musenalm_id": {
      "type": "number"
    },
    "created": {
      "type": "string",
      "readOnly": true
    },
    "updated": {
      "type": "string",
      "readOnly": true
    },
    "edit_state": {
      "type": "string",
      "enum": [
        "Unknown",
        "ToDo",
        "Seen",
        "Partially Edited",
        "Waiting",
        "Review",
        "Edited",
        ""
      ]
    },
    "annotation": {
      "type": "string",
      "x-content": "markdown"
    },
    "edit_comment": {
      "type": "string",
      "x-content": "markdown"
    },
    "editor": {
      "type": "string",
      "description": "Source users ID; that collection was not included in the export.",
      "readOnly": true
    },
    "agents": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "properties": {
          "source_id": {
            "type": "string",
            "minLength": 15,
            "maxLength": 15,
            "pattern": "^[a-z0-9]+$",
            "readOnly": true
          },
          "agent": {
            "type": "string",
            "x-relation": {
              "collection": "agents"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "Autor:in",
              "Herausgeber:in",
              "Verlag",
              "Druck",
              "Vertrieb",
              "Zeichner:in",
              "Komponist:in",
              "Künstler:in",
              "Übersetzer:in",
              "Redakteur:in",
              "Kartograf:in",
              "Kupferstecher:in",
              "Dargestellt"
            ]
          },
          "conjecture": {
            "type": "boolean"
          },
          "uncertain": {
            "type": "boolean"
          },
          "created": {
            "type": "string",
            "readOnly": true
          },
          "updated": {
            "type": "string",
            "readOnly": true
          },
          "annotation": {
            "type": "string",
            "x-content": "markdown"
          },
          "edit_comment": {
            "type": "string",
            "x-content": "markdown"
          }
        },
        "required": [
          "agent"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "preferred_title",
    "musenalm_id"
  ],
  "additionalProperties": false
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/6ahcv866w15aojt.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-15 10:59:38.655Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "9",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 140003,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Text"
  ],
  "numbering": 4,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "A MESSIEURS / LES / JOURNALISTES.",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "A MESSIEURS / LES / JOURNALISTES.",
  "updated": "2026-06-15 11:16:19.007Z",
  "variant_title": "",
  "year": 1786,
  "editor": "hbwf3kmsfyyeo1u",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/vzzs5wsfva6z130.json
{
  "annotation": "Graphik (Portrait) im Kalendarium Februar",
  "content_type": [],
  "created": "2026-06-11 10:18:31.834Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 96268,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 6,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Johannes Austriacus / Princeps Francoevillae",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [
    "alm_2185_96268_kk8vs5ab77.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Johannes Austriacus / Princeps Francoevillae",
  "updated": "2010-01-27 00:00:00.000Z",
  "variant_title": "",
  "year": 1802,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/5us1uh9wr6pge3q.json
{
  "annotation": "paginiert 1 /) Illustration zu »Beschreibung des Gartens in Hohenheim. Zweite Fortsetzung. / Der Zirkelbau« von G. H. Rapp INr 74217, Obj 11 /) # Zuschreibung: Fischer S. 244",
  "content_type": [],
  "created": "2026-06-11 10:18:17.536Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "66",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 74216,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 10,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Der Zirkelbau",
  "pseudonym": true,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [
    "alm_3110_74216_0gm5c0rumc.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Der Zirkelbau",
  "updated": "2010-02-26 00:00:00.000Z",
  "variant_title": "",
  "year": 1797,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:00.525Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:00.525Z",
      "agent": "yos6i167q0dzqb7",
      "source_id": "moz9447guoeyeg8"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/u0pxrw1oyv87dfe.json
{
  "annotation": "Illustration zu »Die Odilienhöhe« von K. Geib INr 63248, Obj 12",
  "content_type": [],
  "created": "2026-06-11 10:18:10.202Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 63256,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 20,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Rheinische Sagen. / Romanzen von C. Geib",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "G. Opitz del. Fleischmann sc.",
  "scans": [
    "alm_1036_63256_kmqwnwa0cz.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Rheinische Sagen. / Romanzen von C. Geib",
  "updated": "2009-04-07 00:00:00.000Z",
  "variant_title": "",
  "year": 1828,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:59.984Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:59.984Z",
      "agent": "t4jzdbiq2oijmzh",
      "source_id": "185c34kryfqrpam"
    },
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:59.984Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:59.984Z",
      "agent": "1mpfrjn3gtg55av",
      "source_id": "iiadky80yv1a5l0"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/bnlarjhtr6r56up.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11 10:18:45.936Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "141",
  "incipit_statement": "Am dämmernden Horizonte, / Im scheidenden Abendlicht / Glühet die Stadt,",
  "language": [],
  "musenalm_id": 117688,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 39,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Abendläuten",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Ant. Langer",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Abendläuten",
  "updated": "2017-03-17 00:00:00.000Z",
  "variant_title": "",
  "year": 1847,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:02.685Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:02.685Z",
      "agent": "5vrpezk8s9sgvqz",
      "source_id": "idt0qoa6ryaotmv"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/xpxv7p5hhthksrf.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11 10:18:01.315Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 41466,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 19,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Basalt-aehnliches Gebirge bei Monterey oberhalb Californiens",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [
    "alm_541_41466_b5a9kiwsi2.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Basalt-aehnliches Gebirge bei Monterey oberhalb Californiens",
  "updated": "2005-11-28 00:00:00.000Z",
  "variant_title": "",
  "year": 1805,
  "editor": "",
  "agents": []
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/ah8gdvetj8ge0ei.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11 10:17:41.176Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "202",
  "incipit_statement": "Wer möchte sich an Schattenbildern weiden, / Die mit erborgtem Schein das Wesen überkleiden,",
  "language": [],
  "musenalm_id": 1327,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 71,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Poesie des Lebens. / An **",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "SCHILLER",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Poesie des Lebens. / An **",
  "updated": "2000-07-28 00:00:00.000Z",
  "variant_title": "",
  "year": 1799,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:56.711Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:56.711Z",
      "agent": "z7x6qq4zgxumydc",
      "source_id": "mlyt1zaesrdkm1u"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/mgzuqnsqtp4m68y.json
{
  "annotation": "Lenz-Kommando. Liederscherz (Sammlung INr 103817, Obj 53)",
  "content_type": [],
  "created": "2026-06-11 10:18:35.486Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "327",
  "incipit_statement": "Halt, sag' ich, halt! Nicht weiter! / Nun steht die Fronte da,",
  "language": [],
  "musenalm_id": 103819,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 55,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "2. / Halt",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Joh. Gabriel Seidl",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "2. / Halt",
  "updated": "2010-01-21 00:00:00.000Z",
  "variant_title": "",
  "year": 1838,
  "editor": "",
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:19:02.043Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11 10:19:02.043Z",
      "agent": "uto0tazb8xl0ih3",
      "source_id": "gx15rrsaiu94rgl"
    }
  ]
}
