=== Simon-Martens/objekte/examples/musenalm/.objekte/collections/contents.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "annotation": {
      "type": "string"
    },
    "content_type": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "contributors": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "agents": {
            "type": "string",
            "x-relation": {
              "collection": "agents"
            }
          },
          "annotation": {
            "type": "string"
          },
          "conjecture": {
            "type": "boolean"
          },
          "created": {
            "type": "string"
          },
          "edit_comment": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "type": {
            "enum": [
              "Autor:in",
              "Herausgeber:in",
              "Komponist:in",
              "Kupferstecher:in",
              "Künstler:in",
              "Verlag",
              "Zeichner:in"
            ],
            "type": "string"
          },
          "uncertain": {
            "type": "boolean"
          },
          "updated": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "agents",
          "type"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "created": {
      "type": "string"
    },
    "dimensions": {
      "type": "string"
    },
    "edit_comment": {
      "type": "string"
    },
    "edit_state": {
      "enum": [
        "Edited"
      ],
      "index": true,
      "type": "string"
    },
    "editor": {
      "enum": [
        "",
        "gpj6tpa1lmk3vpy",
        "hbwf3kmsfyyeo1u"
      ],
      "index": true,
      "type": "string"
    },
    "entry": {
      "index": true,
      "type": "string",
      "x-relation": {
        "collection": "entries"
      }
    },
    "extent": {
      "type": "string"
    },
    "incipit_statement": {
      "type": "string"
    },
    "language": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "musenalm_id": {
      "index": true,
      "type": "integer"
    },
    "musenalm_pagination": {
      "items": {
        "enum": [
          "1. Arabische Seitenzählung",
          "1. Römische Seitenzählung",
          "2. Arabische Seitenzählung",
          "2. Römische Seitenzählung",
          "3. Arabische Seitenzählung",
          "4. Arabische Seitenzählung",
          "5. Arabische Seitenzählung",
          "6. Arabische Seitenzählung",
          "Arabische Seitenzählung",
          "Römische Seitenzählung"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "musenalm_type": {
      "items": {
        "enum": [
          "Corrigenda",
          "Diagramm",
          "Gedicht/Lied",
          "Graphik",
          "Graphik-Verzeichnis",
          "Inhaltsverzeichnis",
          "Kalendarium",
          "Karte",
          "Motto",
          "Musikbeigabe",
          "Musikbeigaben-Verzeichnis",
          "Prosa",
          "Rätsel",
          "Sammlung",
          "Spiegel",
          "Tabelle",
          "Tafel",
          "Text",
          "Titel",
          "Trinkspruch",
          "Umschlag",
          "Widmung",
          "graph. Anleitung",
          "graph. Strickanleitung",
          "graph. Tanzanleitung",
          "szen. Darstellung"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "numbering": {
      "index": true,
      "type": "number"
    },
    "parallel_title": {
      "type": "string"
    },
    "place_statement": {
      "type": "string"
    },
    "preferred_title": {
      "type": "string"
    },
    "pseudonym": {
      "index": true,
      "type": "boolean"
    },
    "publication_statement": {
      "type": "string"
    },
    "responsibility_statement": {
      "type": "string"
    },
    "scans": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "subtitle_statement": {
      "type": "string"
    },
    "title_statement": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "variant_title": {
      "type": "string"
    },
    "year": {
      "index": true,
      "type": "integer"
    }
  },
  "required": [
    "preferred_title",
    "musenalm_id",
    "entry"
  ],
  "type": "object",
  "x-index-paths": [
    "contributors[*].conjecture",
    "contributors[*].type",
    "contributors[*].uncertain",
    "musenalm_pagination[*]",
    "musenalm_type[*]"
  ],
  "x-objekte": {
    "name": "contents",
    "path": "data/contents",
    "type": "data",
    "format": "json",
    "id": "filename"
  }
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/qkkgbgufvbifclu.json
{
  "annotation": "V. Anekdoten und Karakterzüge aus der Theaterwelt (Sammlung INr 115575, Obj 14)",
  "content_type": [],
  "created": "2026-06-11T10:18:43.521Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "203",
  "incipit_statement": "Während Schus Aufenthalt in Breslau meldete sich zur Aufnahme in seine Gesellschaft ein junges, munteres Weibchen,",
  "language": [],
  "musenalm_id": 115584,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Prosa"
  ],
  "numbering": 23,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Während Schus Aufenthalt in Breslau meldete sich zur Aufnahme in seine Gesellschaft ein junges, munteres Weibchen,…",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "",
  "updated": "2010-01-07T00:00:00.000Z",
  "variant_title": "",
  "year": 1808,
  "editor": "",
  "contributors": [],
  "entry": "cudt9uyg4rvlc10"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/4dbycsrn1gpm7ld.json
{
  "annotation": "# s. Re 39",
  "content_type": [],
  "created": "2026-06-11T10:17:43.307Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "90",
  "incipit_statement": "Dich auch so grausam abzubrechen! / Nicht wahr, mein Blümchen, könntst du sprechen,",
  "language": [],
  "musenalm_id": 5246,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 59,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Der Knabe an ein Vergißmein- / nichtblümchen",
  "pseudonym": true,
  "publication_statement": "",
  "responsibility_statement": "Z.",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Der Knabe an ein Vergißmein- / nichtblümchen",
  "updated": "2000-10-17T00:00:00.000Z",
  "variant_title": "",
  "year": 1776,
  "editor": "",
  "contributors": [
    {
      "id": "o0bycy6hicccryd",
      "agents": "qh3g3sytdf754hd",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:18:57.070Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:18:57.070Z"
    }
  ],
  "entry": "bxsg9p18jlqw6e0"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/jpjl5xnk3u1w9he.json
{
  "annotation": "IV. Kleine Abhandlungen und Aufsätze (Sammlung INr 15453, Obj 43) # Bezeichnung aus dem I-Verz; der Beitrag wird fortgesetzt in: Gartenkalender (Hirschfeld) 1784 INr 15548",
  "content_type": [],
  "created": "2026-06-11T10:17:48.994Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "180",
  "incipit_statement": "Den Blumengarten muß man nothwendig aus einem andern Gesichtspuncte betrachten, als jene großen Anlagen,",
  "language": [],
  "musenalm_id": 15458,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Text"
  ],
  "numbering": 49,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Etwas über die Ausschmückung der Blumengärten",
  "pseudonym": true,
  "publication_statement": "",
  "responsibility_statement": "Prof. Weber in Kiel",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Etwas über die Ausschmückung der Blumengärten",
  "updated": "2001-05-18T00:00:00.000Z",
  "variant_title": "",
  "year": 1783,
  "editor": "",
  "contributors": [],
  "entry": "uz0plg0m9qs6qe8"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/cxwxi4gftraqn78.json
{
  "annotation": "Silhouette nummeriert XXXXIV; »Gesang und kunstvolles Spiel«",
  "content_type": [],
  "created": "2026-06-11T10:18:53.721Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 133865,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 56,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Anna Storace",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [
    "alm_4863_133865_zxiw9pku7d.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Anna Storace",
  "updated": "2023-12-06T00:00:00.000Z",
  "variant_title": "",
  "year": 1786,
  "editor": "",
  "contributors": [],
  "entry": "7xwxvdct5jkx6nu"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/1b3hwoxtonzfi04.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:17:52.945Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "139",
  "incipit_statement": "Durchs Leben macht ich einen Gang, / Er schien mir kurz und währte lang.",
  "language": [],
  "musenalm_id": 24511,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 89,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Lebensfragmente",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Ulrich Hegner",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Lebensfragmente",
  "updated": "2002-06-05T00:00:00.000Z",
  "variant_title": "",
  "year": 1832,
  "editor": "",
  "contributors": [
    {
      "id": "wc4xmibsl4vnpvo",
      "agents": "5xr1i06rwmguu38",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:18:58.192Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:18:58.192Z"
    }
  ],
  "entry": "9am5244vyejx2gg"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/klgya396ggy5180.json
{
  "annotation": "V. Bemerkungen, Anekdoten und Einfälle (Sammlung INr 11129, Obj 25) /) Prosaische Aufsätze (Sammlung INr 11121, Obj 16)",
  "content_type": [],
  "created": "2026-06-11T10:17:45.110Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "158",
  "incipit_statement": "Diese Prinzessin des Königs von Pohlen und Churfürstens von Sachsen, August des Dritten,",
  "language": [],
  "musenalm_id": 11130,
  "musenalm_pagination": [
    "1. Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Prosa"
  ],
  "numbering": 26,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "1. / Marie Josephe, Dauphine von Frankreich, / geborne Prinzessin von Pohlen",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Kretschmann",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "1. / Marie Josephe, Dauphine von Frankreich, / geborne Prinzessin von Pohlen",
  "updated": "2001-02-21T00:00:00.000Z",
  "variant_title": "",
  "year": 1799,
  "editor": "",
  "contributors": [
    {
      "id": "u0hfdp8afk9ye3y",
      "agents": "r6akxiph7cy43x3",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:18:57.316Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:18:57.316Z"
    }
  ],
  "entry": "knzr0dlijjvs2z3"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/svsyt8h395rx0aw.json
{
  "annotation": "#$ lt. Re 39: vielleicht Boie",
  "content_type": [],
  "created": "2026-06-11T10:17:49.980Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "89",
  "incipit_statement": "Auf Erden, im Olymp, ist nichts wie Sie so / schön!",
  "language": [],
  "musenalm_id": 16965,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 42,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Amanda",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "X. #$",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Amanda",
  "updated": "2001-08-02T00:00:00.000Z",
  "variant_title": "",
  "year": 1786,
  "editor": "",
  "contributors": [],
  "entry": "m6qmlvsue6mq3y2"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/1nwc73yqmkoix0o.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:18:36.007Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "107",
  "incipit_statement": "Wir fleh'n dich an, komm', heil'ger Geist, / Herab zu deinen Knechten,",
  "language": [],
  "musenalm_id": 101382,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 61,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Ziel des Menschen",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Zacharias Werner",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Ziel des Menschen",
  "updated": "2010-02-11T00:00:00.000Z",
  "variant_title": "",
  "year": 1831,
  "editor": "",
  "contributors": [
    {
      "id": "ommiweikbfwfn50",
      "agents": "g7f1xv6d8kkyhx1",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:19:02.078Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:19:02.078Z"
    }
  ],
  "entry": "yg0ab49sckkt22e"
}
