=== Simon-Martens/objekte/examples/musenalm/.objekte/collections/contents.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "annotation": {
      "type": "string"
    },
    "content_type": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "contributors": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "agents": {
            "type": "string",
            "x-relation": {
              "collection": "agents"
            }
          },
          "annotation": {
            "type": "string"
          },
          "conjecture": {
            "type": "boolean"
          },
          "created": {
            "type": "string"
          },
          "edit_comment": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "type": {
            "enum": [
              "Autor:in",
              "Herausgeber:in",
              "Komponist:in",
              "Kupferstecher:in",
              "Künstler:in",
              "Verlag",
              "Zeichner:in"
            ],
            "type": "string"
          },
          "uncertain": {
            "type": "boolean"
          },
          "updated": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "agents",
          "type"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "created": {
      "type": "string"
    },
    "dimensions": {
      "type": "string"
    },
    "edit_comment": {
      "type": "string"
    },
    "edit_state": {
      "enum": [
        "Edited"
      ],
      "index": true,
      "type": "string"
    },
    "editor": {
      "enum": [
        "",
        "gpj6tpa1lmk3vpy",
        "hbwf3kmsfyyeo1u"
      ],
      "index": true,
      "type": "string"
    },
    "entry": {
      "index": true,
      "type": "string",
      "x-relation": {
        "collection": "entries"
      }
    },
    "extent": {
      "type": "string"
    },
    "incipit_statement": {
      "type": "string"
    },
    "language": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "musenalm_id": {
      "index": true,
      "type": "integer"
    },
    "musenalm_pagination": {
      "items": {
        "enum": [
          "1. Arabische Seitenzählung",
          "1. Römische Seitenzählung",
          "2. Arabische Seitenzählung",
          "2. Römische Seitenzählung",
          "3. Arabische Seitenzählung",
          "4. Arabische Seitenzählung",
          "5. Arabische Seitenzählung",
          "6. Arabische Seitenzählung",
          "Arabische Seitenzählung",
          "Römische Seitenzählung"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "musenalm_type": {
      "items": {
        "enum": [
          "Corrigenda",
          "Diagramm",
          "Gedicht/Lied",
          "Graphik",
          "Graphik-Verzeichnis",
          "Inhaltsverzeichnis",
          "Kalendarium",
          "Karte",
          "Motto",
          "Musikbeigabe",
          "Musikbeigaben-Verzeichnis",
          "Prosa",
          "Rätsel",
          "Sammlung",
          "Spiegel",
          "Tabelle",
          "Tafel",
          "Text",
          "Titel",
          "Trinkspruch",
          "Umschlag",
          "Widmung",
          "graph. Anleitung",
          "graph. Strickanleitung",
          "graph. Tanzanleitung",
          "szen. Darstellung"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "numbering": {
      "index": true,
      "type": "number"
    },
    "parallel_title": {
      "type": "string"
    },
    "place_statement": {
      "type": "string"
    },
    "preferred_title": {
      "type": "string"
    },
    "pseudonym": {
      "index": true,
      "type": "boolean"
    },
    "publication_statement": {
      "type": "string"
    },
    "responsibility_statement": {
      "type": "string"
    },
    "scans": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "subtitle_statement": {
      "type": "string"
    },
    "title_statement": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "variant_title": {
      "type": "string"
    },
    "year": {
      "index": true,
      "type": "integer"
    }
  },
  "required": [
    "preferred_title",
    "musenalm_id",
    "entry"
  ],
  "type": "object",
  "x-index-paths": [
    "contributors[*].conjecture",
    "contributors[*].type",
    "contributors[*].uncertain",
    "musenalm_pagination[*]",
    "musenalm_type[*]"
  ],
  "x-objekte": {
    "name": "contents",
    "path": "data/contents",
    "type": "data",
    "format": "json",
    "id": "filename"
  }
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/942e2nhyzfa3hsd.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:18:52.897Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "94",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 130711,
  "musenalm_pagination": [
    "2. Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Text"
  ],
  "numbering": 21,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "13. Carl Fischer",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "13. Carl Fischer",
  "updated": "2010-02-23T00:00:00.000Z",
  "variant_title": "",
  "year": 1836,
  "editor": "",
  "contributors": [],
  "entry": "5lh8wo9m4rix0p5"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/pbph20rscmr8y19.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:18:04.174Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 51966,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Karte"
  ],
  "numbering": 26,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Der Canton / Glarus",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Gez. von H. Keller Gest. v. J. Scheurmann",
  "scans": [
    "alm_709_51966_6li3yijzwc.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "Der Canton / Glarus",
  "updated": "2007-10-02T00:00:00.000Z",
  "variant_title": "",
  "year": 1809,
  "editor": "",
  "contributors": [
    {
      "id": "l9y8n0wcvmf6u84",
      "agents": "hp3ztaqa2ipzjih",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:18:59.546Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:18:59.546Z"
    },
    {
      "id": "ofg75j2svbz06nj",
      "agents": "9ql0nfn99kgr5a3",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:18:59.547Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:18:59.547Z"
    }
  ],
  "entry": "2z9wdi3rztqdz5t"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/d5c479jp6ppyv31.json
{
  "annotation": "<div>Vortitel</div>",
  "content_type": [],
  "created": "2026-06-15T10:43:43.878Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "1",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 140000,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Titel"
  ],
  "numbering": 1,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "ALMANACH / NOUVEAU / DE L’AN PASSÉ, / OU / L’ALMANACH PUCE. / No. 2.",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "ALMANACH / NOUVEAU / DE L’AN PASSÉ, / OU / L’ALMANACH PUCE. / No. 2.",
  "updated": "2026-06-15T11:16:19.005Z",
  "variant_title": "",
  "year": 1786,
  "editor": "hbwf3kmsfyyeo1u",
  "contributors": [],
  "entry": "ez5st062mqvgvpd"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/rqf36faoeh7celo.json
{
  "annotation": "2 Sammlungen mit 8 Rätseln INr 22472-22481, Obj 95-104",
  "content_type": [],
  "created": "2026-06-11T10:17:51.908Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "416",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 22471,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Sammlung"
  ],
  "numbering": 94,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Charaden und Räthsel",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Charaden und Räthsel",
  "updated": "2002-02-28T00:00:00.000Z",
  "variant_title": "",
  "year": 1822,
  "editor": "",
  "contributors": [],
  "entry": "6fmihr0nycsi5f1"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/pxt4a7mcq8zb7fy.json
{
  "annotation": "Beilagen (Sammlung INr 9080, Obj 38)",
  "content_type": [],
  "created": "2026-06-11T10:17:46.571Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "303",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 9082,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Text",
    "Tabelle"
  ],
  "numbering": 40,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "II. / Etat / aller / OberBefehlshaber / der / Armeen und Flotten / der fränkischen Republik, / zur Epoche des Nov. 1795",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "II. / Etat / aller / OberBefehlshaber / der / Armeen und Flotten / der fränkischen Republik, / zur Epoche des Nov. 1795",
  "updated": "2001-01-09T00:00:00.000Z",
  "variant_title": "",
  "year": 1798,
  "editor": "",
  "contributors": [],
  "entry": "rcth7xro2nnp91v"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/ngdp6h5wsobs70p.json
{
  "annotation": "Wandergrüße. Erinnerungen aus dem Tagebuche einer Herbstreise (Sammlung INr 81147, Obj 19)",
  "content_type": [],
  "created": "2026-06-11T10:18:21.989Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "195",
  "incipit_statement": "Weißt du, Geliebte, was ich Geträumt die jüngste Nacht,",
  "language": [],
  "musenalm_id": 81167,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 39,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Der Traum",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Heinrich Stieglitz",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Der Traum",
  "updated": "2008-07-31T00:00:00.000Z",
  "variant_title": "",
  "year": 1837,
  "editor": "",
  "contributors": [
    {
      "id": "4bdlkchuj1abkvn",
      "agents": "1obisuoppirekjz",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:19:00.838Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:19:00.838Z"
    }
  ],
  "entry": "bi5go8hqv4g3rf5"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/c0vbqzcncuc4s72.json
{
  "annotation": "mit 3 Illustrationen s. Graphiken INr 103605-103607, Obj 22-24",
  "content_type": [],
  "created": "2026-06-11T10:18:38.196Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "45",
  "incipit_statement": "Es ging wohl schon Mancher in die Fremde, und da er zurückkahm, hat er seine Heimath nicht mehr erkannt mit Haus und Hof,",
  "language": [],
  "musenalm_id": 103604,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Prosa"
  ],
  "numbering": 21,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Das / Strafgericht der Eidgenossen. / (1587.)",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Das / Strafgericht der Eidgenossen. / (1587.)",
  "updated": "2010-03-12T00:00:00.000Z",
  "variant_title": "",
  "year": 1849,
  "editor": "",
  "contributors": [
    {
      "id": "nvt4urtezttq8mx",
      "agents": "jo3symqxy3hqpd5",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:19:02.200Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:19:02.200Z"
    }
  ],
  "entry": "fzl1t9ff6hq96cw"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/8tvrw7yxbyxonq8.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:17:51.557Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "287",
  "incipit_statement": "Es ist gescheh'n: die Anker sind gelichtet; / Ich stosse frey von Ihres Eylands Strand:",
  "language": [],
  "musenalm_id": 21991,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Gedicht/Lied"
  ],
  "numbering": 155,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "An die Musen. / Sonnett",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "Siegmar",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "An die Musen. / Sonnett",
  "updated": "2002-02-11T00:00:00.000Z",
  "variant_title": "",
  "year": 1800,
  "editor": "",
  "contributors": [],
  "entry": "y398dlaujaue6el"
}
