=== Simon-Martens/objekte/examples/musenalm/.objekte/collections/contents.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "annotation": {
      "type": "string"
    },
    "content_type": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "contributors": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "agents": {
            "type": "string",
            "x-relation": {
              "collection": "agents"
            }
          },
          "annotation": {
            "type": "string"
          },
          "conjecture": {
            "type": "boolean"
          },
          "created": {
            "type": "string"
          },
          "edit_comment": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "type": {
            "enum": [
              "Autor:in",
              "Herausgeber:in",
              "Komponist:in",
              "Kupferstecher:in",
              "Künstler:in",
              "Verlag",
              "Zeichner:in"
            ],
            "type": "string"
          },
          "uncertain": {
            "type": "boolean"
          },
          "updated": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "agents",
          "type"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "created": {
      "type": "string"
    },
    "dimensions": {
      "type": "string"
    },
    "edit_comment": {
      "type": "string"
    },
    "edit_state": {
      "enum": [
        "Edited"
      ],
      "index": true,
      "type": "string"
    },
    "editor": {
      "enum": [
        "",
        "gpj6tpa1lmk3vpy",
        "hbwf3kmsfyyeo1u"
      ],
      "index": true,
      "type": "string"
    },
    "entry": {
      "index": true,
      "type": "string",
      "x-relation": {
        "collection": "entries"
      }
    },
    "extent": {
      "type": "string"
    },
    "incipit_statement": {
      "type": "string"
    },
    "language": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "musenalm_id": {
      "index": true,
      "type": "integer"
    },
    "musenalm_pagination": {
      "items": {
        "enum": [
          "1. Arabische Seitenzählung",
          "1. Römische Seitenzählung",
          "2. Arabische Seitenzählung",
          "2. Römische Seitenzählung",
          "3. Arabische Seitenzählung",
          "4. Arabische Seitenzählung",
          "5. Arabische Seitenzählung",
          "6. Arabische Seitenzählung",
          "Arabische Seitenzählung",
          "Römische Seitenzählung"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "musenalm_type": {
      "items": {
        "enum": [
          "Corrigenda",
          "Diagramm",
          "Gedicht/Lied",
          "Graphik",
          "Graphik-Verzeichnis",
          "Inhaltsverzeichnis",
          "Kalendarium",
          "Karte",
          "Motto",
          "Musikbeigabe",
          "Musikbeigaben-Verzeichnis",
          "Prosa",
          "Rätsel",
          "Sammlung",
          "Spiegel",
          "Tabelle",
          "Tafel",
          "Text",
          "Titel",
          "Trinkspruch",
          "Umschlag",
          "Widmung",
          "graph. Anleitung",
          "graph. Strickanleitung",
          "graph. Tanzanleitung",
          "szen. Darstellung"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "numbering": {
      "index": true,
      "type": "number"
    },
    "parallel_title": {
      "type": "string"
    },
    "place_statement": {
      "type": "string"
    },
    "preferred_title": {
      "type": "string"
    },
    "pseudonym": {
      "index": true,
      "type": "boolean"
    },
    "publication_statement": {
      "type": "string"
    },
    "responsibility_statement": {
      "type": "string"
    },
    "scans": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "subtitle_statement": {
      "type": "string"
    },
    "title_statement": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "variant_title": {
      "type": "string"
    },
    "year": {
      "index": true,
      "type": "integer"
    }
  },
  "required": [
    "preferred_title",
    "musenalm_id",
    "entry"
  ],
  "type": "object",
  "x-index-paths": [
    "contributors[*].conjecture",
    "contributors[*].type",
    "contributors[*].uncertain",
    "musenalm_pagination[*]",
    "musenalm_type[*]"
  ],
  "x-objekte": {
    "name": "contents",
    "path": "data/contents",
    "type": "data",
    "format": "json",
    "id": "filename"
  }
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/mc5kbgt0pf3gmj4.json
{
  "annotation": "Figuren (Sammlung von Tanzanleitungen INr 9491, Obj 339) s. Musikbeigaben INr 9503-9512, Obj 350-359",
  "content_type": [],
  "created": "2026-06-11T10:17:44.457Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "279",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 9498,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Sammlung"
  ],
  "numbering": 345,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "[Figuren zu vier und sechstourigen Anglaisen, nach sehr beliebiger Musik.] Anglaisen mit sechs Touren",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "[Figuren zu vier und sechstourigen Anglaisen, nach sehr beliebiger Musik.] Anglaisen mit sechs Touren",
  "updated": "2001-01-22T00:00:00.000Z",
  "variant_title": "",
  "year": 1791,
  "editor": "",
  "contributors": [],
  "entry": "bb6scl8yhe0ekb9"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/9xf6q1rrk2phrln.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:17:45.089Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "148",
  "incipit_statement": "Ehe noch Welschland, Paris oder London das Urbild für modische Damen und Herren in Deutschland ward, genoß diese Ehre Burgund.",
  "language": [],
  "musenalm_id": 7013,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Text"
  ],
  "numbering": 32,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Pluderhosen und Teufeleyen, / ein / Paar Modesachen / des sechszehnten Jahrhunderts",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Pluderhosen und Teufeleyen, / ein / Paar Modesachen / des sechszehnten Jahrhunderts",
  "updated": "2000-11-23T00:00:00.000Z",
  "variant_title": "",
  "year": 1789,
  "editor": "",
  "contributors": [],
  "entry": "gmzhgcvdg5d4w7t"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/ntsmwad63noa6k7.json
{
  "annotation": "Nachtitel",
  "content_type": [],
  "created": "2026-06-11T10:18:28.799Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 96408,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Titel"
  ],
  "numbering": 4,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "Rastatter / Taschenbuch / auf / 1802",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "Rastatter / Taschenbuch / auf / 1802",
  "updated": "2014-05-07T00:00:00.000Z",
  "variant_title": "",
  "year": 1802,
  "editor": "",
  "contributors": [],
  "entry": "g0plntt2k4mvdhy"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/1nzx9y7opv3au9l.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:18:27.197Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "111",
  "incipit_statement": "Gesegnet seyen die Thränen! Sie sind der Lethestrom, in dem das belastete Herz seine Bürden wirft, das Taufwasser, womit der Sterbliche seine Schmerzen und Wonnen tauft,",
  "language": [],
  "musenalm_id": 87420,
  "musenalm_pagination": [
    "Arabische Seitenzählung"
  ],
  "musenalm_type": [
    "Prosa"
  ],
  "numbering": 51,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "1. / Ueber die Thränen. / Phantasie",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "1. / Ueber die Thränen. / Phantasie",
  "updated": "2009-07-23T00:00:00.000Z",
  "variant_title": "",
  "year": 1822,
  "editor": "",
  "contributors": [],
  "entry": "nmxrnzhm1luljk3"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/hxro7o4vkcdqknw.json
{
  "annotation": "",
  "content_type": [],
  "created": "2026-06-11T10:18:15.803Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "3",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 77634,
  "musenalm_pagination": [
    "Römische Seitenzählung"
  ],
  "musenalm_type": [
    "Inhaltsverzeichnis",
    "Graphik-Verzeichnis"
  ],
  "numbering": 4,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "[Inhaltsverzeichnis, Graphik-Verzeichnis]",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [],
  "subtitle_statement": "",
  "title_statement": "",
  "updated": "2010-02-02T00:00:00.000Z",
  "variant_title": "",
  "year": 1838,
  "editor": "",
  "contributors": [],
  "entry": "90ka8lv1gxz90mj"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/82x9q6egbvhxqwt.json
{
  "annotation": "Graphik im Kalendarium Juni; paginiert 6. /) Illustration zu »Liebe und kindliche Pflicht« INr 61516, Obj 33",
  "content_type": [],
  "created": "2026-06-11T10:18:10.646Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 61501,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 18,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "O! meine Tochter!",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [
    "alm_981_61501_esx34um1sq.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "O! meine Tochter!",
  "updated": "2009-01-15T00:00:00.000Z",
  "variant_title": "",
  "year": 1817,
  "editor": "",
  "contributors": [],
  "entry": "eao2h9iqgsabmlt"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/o9n3tdmghpzz6s7.json
{
  "annotation": "Umschlaggraphik r.",
  "content_type": [],
  "created": "2026-06-11T10:18:46.639Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 119601,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 0.1,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "RHEINISCHES / TASCHENBUCH. / 1844",
  "pseudonym": false,
  "publication_statement": "",
  "responsibility_statement": "unbezeichnet",
  "scans": [
    "alm_599_119601_nnfevpp10z.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "RHEINISCHES / TASCHENBUCH. / 1844",
  "updated": "2006-06-27T00:00:00.000Z",
  "variant_title": "",
  "year": 1844,
  "editor": "",
  "contributors": [],
  "entry": "y3e8c3pdmkctt6x"
}

=== Simon-Martens/objekte/examples/musenalm/data/contents/xg1gx5gn4afp0gn.json
{
  "annotation": "# Bez. am 1. Blatt der Suite /) Graphik im Kalendarium Dezember paginiert 12.; Illustration zu »Sophiens Reise von Memel nach Sachsen« von Joh. Tim. Hermes /) mit Erläuterungen im G-Verz INr 58392, Obj 18",
  "content_type": [],
  "created": "2026-06-11T10:17:42.087Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_state": "Edited",
  "extent": "",
  "incipit_statement": "",
  "language": [],
  "musenalm_id": 58391,
  "musenalm_pagination": [],
  "musenalm_type": [
    "Graphik"
  ],
  "numbering": 17,
  "parallel_title": "",
  "place_statement": "",
  "preferred_title": "[Graphik (D. Chodowiecki inv. et del. D. Berger sc. Berolini)]",
  "pseudonym": true,
  "publication_statement": "",
  "responsibility_statement": "D. Chodowiecki inv. et del. D. Berger sc. Berolini",
  "scans": [
    "alm_789_58391_v0bgyaq08m.jpg"
  ],
  "subtitle_statement": "",
  "title_statement": "",
  "updated": "2008-06-23T00:00:00.000Z",
  "variant_title": "",
  "year": 1778,
  "editor": "",
  "contributors": [
    {
      "id": "3bjlnffkknx5hiq",
      "agents": "frgalfp04iv5xmo",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:18:56.901Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:18:56.901Z"
    },
    {
      "id": "dd4ifo2ulon4b8o",
      "agents": "qtx54xtziq79pnc",
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11T10:18:56.901Z",
      "edit_comment": "",
      "type": "Autor:in",
      "uncertain": false,
      "updated": "2026-06-11T10:18:56.901Z"
    }
  ],
  "entry": "swq6xbop7jt3zd0"
}
