=== Simon-Martens/objekte/examples/musenalm/.editor/collections/entries/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "agents": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "agent": {
            "type": "string",
            "x-relation": {
              "collection": "agents"
            }
          },
          "annotation": {
            "type": "string"
          },
          "conjecture": {
            "type": "boolean"
          },
          "created": {
            "type": "string"
          },
          "edit_comment": {
            "type": "string"
          },
          "source_id": {
            "type": "string"
          },
          "type": {
            "enum": [
              "Druck",
              "Herausgeber:in",
              "Verlag"
            ],
            "type": "string"
          },
          "uncertain": {
            "type": "boolean"
          },
          "updated": {
            "type": "string"
          }
        },
        "required": [
          "agent"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "annotation": {
      "type": "string"
    },
    "carrier_type": {
      "items": {
        "enum": [
          "Band"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "content_type": {
      "items": {
        "enum": [
          "Text",
          "unbewegtes Bild"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "created": {
      "type": "string"
    },
    "dimensions": {
      "type": "string"
    },
    "edit_comment": {
      "type": "string"
    },
    "edit_fielddata": {
      "properties": {
        "places": {
          "properties": {
            "conjecture": {
              "type": "boolean"
            }
          },
          "type": "object"
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "edit_state": {
      "enum": [
        "Edited",
        "Review",
        "Seen",
        "ToDo",
        "Unknown"
      ],
      "index": true,
      "type": "string"
    },
    "edition": {
      "type": "string"
    },
    "editor": {
      "enum": [
        "",
        "gpj6tpa1lmk3vpy",
        "hbwf3kmsfyyeo1u"
      ],
      "index": true,
      "type": "string"
    },
    "extent": {
      "type": "string"
    },
    "incipit_statement": {
      "type": "string"
    },
    "items": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "annotation": {
            "type": "string"
          },
          "basis": {
            "type": "boolean"
          },
          "condition": {
            "enum": [
              "",
              "1b",
              "2b",
              "3b",
              "40",
              "4b",
              "5b",
              "6b",
              "80",
              "90"
            ],
            "type": "string"
          },
          "created": {
            "type": "string"
          },
          "edit_comment": {
            "type": "string"
          },
          "edit_state": {
            "enum": [
              "",
              "Edited",
              "Review"
            ],
            "type": "string"
          },
          "editor": {
            "type": "string"
          },
          "identifier": {
            "type": "string"
          },
          "location": {
            "type": "string"
          },
          "media": {
            "items": {
              "enum": [
                "Original",
                "Reproduktion"
              ],
              "type": "string"
            },
            "type": "array"
          },
          "owner": {
            "enum": [
              "",
              "Theodor Springmann Stiftung"
            ],
            "type": "string"
          },
          "public": {
            "type": "boolean"
          },
          "scans": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "source_id": {
            "type": "string"
          },
          "updated": {
            "type": "string"
          },
          "uri": {
            "type": "string"
          }
        },
        "required": [],
        "type": "object"
      },
      "type": "array"
    },
    "language": {
      "items": {
        "enum": [
          "fre",
          "ger"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "musenalm_deprecated": {
      "properties": {
        "bearbeitet_am": {
          "type": "string"
        },
        "bearbeitet_von": {
          "enum": [
            "jb",
            "ms"
          ],
          "type": "string"
        },
        "biblio": {
          "type": "integer"
        },
        "erfasst": {
          "type": "boolean"
        },
        "gesichtet": {
          "type": "boolean"
        },
        "norm": {
          "type": "string"
        },
        "reihentitel": {
          "type": "string"
        },
        "status": {
          "items": {
            "enum": [
              "Fremde Herkunft",
              "Original vorhanden",
              "Reprint vorhanden"
            ],
            "type": "string"
          },
          "type": [
            "array",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "musenalm_id": {
      "index": true,
      "type": "integer"
    },
    "parallel_title": {
      "type": "string"
    },
    "place_statement": {
      "type": "string"
    },
    "places": {
      "items": {
        "type": "string",
        "x-relation": {
          "collection": "places"
        }
      },
      "type": "array"
    },
    "preferred_title": {
      "type": "string"
    },
    "pseudonym": {
      "index": true,
      "type": "boolean"
    },
    "publication_statement": {
      "type": "string"
    },
    "refs": {
      "type": "string"
    },
    "responsibility_statement": {
      "type": "string"
    },
    "subtitle_statement": {
      "type": "string"
    },
    "title_statement": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "variant_title": {
      "type": "string"
    },
    "year": {
      "index": true,
      "type": "integer"
    }
  },
  "required": [
    "preferred_title",
    "musenalm_id"
  ],
  "type": "object",
  "x-index-paths": [
    "agents[*].conjecture",
    "agents[*].type",
    "agents[*].uncertain",
    "carrier_type[*]",
    "content_type[*]",
    "edit_fielddata.places.conjecture",
    "items[*].basis",
    "items[*].condition",
    "items[*].edit_state",
    "items[*].media[*]",
    "items[*].owner",
    "items[*].public",
    "language[*]",
    "musenalm_deprecated.bearbeitet_von",
    "musenalm_deprecated.biblio",
    "musenalm_deprecated.erfasst",
    "musenalm_deprecated.gesichtet",
    "musenalm_deprecated.status[*]"
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/entries/2x35zvaqrzhctas.json
{
  "annotation": "",
  "carrier_type": [
    "Band"
  ],
  "content_type": [
    "unbewegtes Bild",
    "Text"
  ],
  "created": "2026-06-11 10:17:37.425Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_fielddata": null,
  "edit_state": "Seen",
  "edition": "",
  "extent": "",
  "incipit_statement": "",
  "language": [
    "ger"
  ],
  "musenalm_deprecated": {
    "reihentitel": "Frauenzimmerkalender (Zürich) 1784",
    "norm": "",
    "biblio": 409940,
    "status": [
      "Original vorhanden"
    ],
    "gesichtet": false,
    "erfasst": false,
    "bearbeitet_am": "2025-06-11T00:00:00",
    "bearbeitet_von": "ms"
  },
  "musenalm_id": 4893,
  "parallel_title": "",
  "place_statement": "Zürich",
  "places": [],
  "preferred_title": "Frauenzimmerkalender (Zürich) 1784",
  "pseudonym": false,
  "publication_statement": "",
  "refs": "nicht bei K; nicht bei L/R",
  "responsibility_statement": "unbezeichnet",
  "subtitle_statement": "",
  "title_statement": "Frauen Zimmer / Calender / Auf das Jahr / 1784 / Zürich bey / Johann Hoffmeister / an der Rosen Gaß",
  "updated": "2026-06-11 10:18:56.034Z",
  "variant_title": "",
  "year": 1784,
  "editor": "",
  "items": [
    {
      "annotation": "",
      "condition": "",
      "created": "2026-06-11 10:17:37.827Z",
      "edit_comment": "",
      "edit_state": "Edited",
      "identifier": "412456",
      "location": "107G06",
      "media": [
        "Original"
      ],
      "owner": "Theodor Springmann Stiftung",
      "scans": [],
      "updated": "2026-06-11 10:17:37.827Z",
      "uri": "",
      "public": false,
      "basis": true,
      "editor": "",
      "source_id": "fc74qwpdrkakhx2"
    }
  ],
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:56.205Z",
      "edit_comment": "",
      "type": "Verlag",
      "uncertain": false,
      "updated": "2026-06-11 10:18:56.205Z",
      "agent": "vjiyycub4l15j8f",
      "source_id": "1sv78yps13y2pte"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/entries/5kojq7iv52mic5q.json
{
  "annotation": "",
  "carrier_type": [
    "Band"
  ],
  "content_type": [
    "unbewegtes Bild",
    "Text"
  ],
  "created": "2026-06-11 10:17:36.738Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_fielddata": null,
  "edit_state": "Edited",
  "edition": "",
  "extent": "VB, verso G, T, SS 1–336 darin 5 GG",
  "incipit_statement": "",
  "language": [
    "ger"
  ],
  "musenalm_deprecated": {
    "reihentitel": "Almanach dramatischer Spiele zur geselligen Unterhaltung auf dem Lande 1812",
    "norm": "~",
    "biblio": 100042,
    "status": [
      "Original vorhanden"
    ],
    "gesichtet": true,
    "erfasst": true,
    "bearbeitet_am": "2010-01-04T00:00:00",
    "bearbeitet_von": "jb"
  },
  "musenalm_id": 1280,
  "parallel_title": "",
  "place_statement": "Leipzig (Hartmann)",
  "places": [
    "d7kbujq7399g22j"
  ],
  "preferred_title": "Almanach dramatischer Spiele zur geselligen Unterhaltung auf dem Lande 1812",
  "pseudonym": false,
  "publication_statement": "",
  "refs": "K 18; L/R 121; Goed VIII. 127, 1",
  "responsibility_statement": "A. von Kotzebue",
  "subtitle_statement": "",
  "title_statement": "ALMANACH / Dramatischer Spiele / zur geselligen Unterhaltung / auf dem Lande / von / A. von KOTZEBUE. / Zehnter Jahrgang / Leipzig / bei C. J. G. Hartmann, / 1812",
  "updated": "2026-06-11 10:18:54.998Z",
  "variant_title": "",
  "year": 1812,
  "editor": "",
  "items": [
    {
      "annotation": "1803-1820?.\nSchwarzer Ledereinband gut erhalten.\n1812: Mit Ku 6(coloriert) und 336 SS.",
      "condition": "3b",
      "created": "2026-06-11 10:17:37.461Z",
      "edit_comment": "",
      "edit_state": "Edited",
      "identifier": "100042",
      "location": "105C05",
      "media": [
        "Original"
      ],
      "owner": "Theodor Springmann Stiftung",
      "scans": [],
      "updated": "2026-06-11 10:17:37.461Z",
      "uri": "",
      "public": false,
      "basis": true,
      "editor": "",
      "source_id": "tlxk2y2wvbzzxbc"
    }
  ],
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:54.873Z",
      "edit_comment": "",
      "type": "Herausgeber:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:54.873Z",
      "agent": "sse24vstbh0jbtd",
      "source_id": "5s0byv0nlqi4imn"
    },
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:55.966Z",
      "edit_comment": "",
      "type": "Verlag",
      "uncertain": false,
      "updated": "2026-06-11 10:18:55.966Z",
      "agent": "p9ks1mekociw0y5",
      "source_id": "dmm1lny8pp8e26x"
    }
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/entries/98hr7d9m9fiqipk.json
{
  "annotation": "",
  "carrier_type": [
    "Band"
  ],
  "content_type": [
    "unbewegtes Bild",
    "Text"
  ],
  "created": "2026-06-11 10:17:36.867Z",
  "dimensions": "",
  "edit_comment": "",
  "edit_fielddata": null,
  "edit_state": "Unknown",
  "edition": "",
  "extent": "",
  "incipit_statement": "",
  "language": [
    "ger"
  ],
  "musenalm_deprecated": {
    "reihentitel": "Freund des schönen Geschlechts, Der 1841",
    "norm": "",
    "biblio": 0,
    "status": null,
    "gesichtet": false,
    "erfasst": false,
    "bearbeitet_am": "2009-01-29T00:00:00",
    "bearbeitet_von": "ms"
  },
  "musenalm_id": 1005,
  "parallel_title": "",
  "place_statement": "Wien",
  "places": [
    "31n865keags4n1n"
  ],
  "preferred_title": "Freund des schönen Geschlechts, Der 1841",
  "pseudonym": false,
  "publication_statement": "",
  "refs": "K 48; L/R 64; Goed VIII. 61, 68a",
  "responsibility_statement": "",
  "subtitle_statement": "",
  "title_statement": "",
  "updated": "2026-06-11 10:18:54.680Z",
  "variant_title": "",
  "year": 1841,
  "editor": "",
  "items": [],
  "agents": [
    {
      "annotation": "",
      "conjecture": false,
      "created": "2026-06-11 10:18:54.791Z",
      "edit_comment": "",
      "type": "Herausgeber:in",
      "uncertain": false,
      "updated": "2026-06-11 10:18:54.791Z",
      "agent": "uto0tazb8xl0ih3",
      "source_id": "mn65dsvwcibl0je"
    }
  ]
}
