=== Simon-Martens/objekte/examples/musenalm/.editor/collections/items/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "annotation": {
      "type": "string"
    },
    "basis": {
      "index": true,
      "type": "boolean"
    },
    "condition": {
      "enum": [
        "",
        "1b",
        "2b",
        "3b",
        "40",
        "4b",
        "5b",
        "6b",
        "80",
        "90"
      ],
      "index": true,
      "type": "string"
    },
    "created": {
      "type": "string"
    },
    "edit_comment": {
      "type": "string"
    },
    "edit_state": {
      "enum": [
        "",
        "Edited",
        "Review"
      ],
      "index": true,
      "type": "string"
    },
    "editor": {
      "type": "string"
    },
    "identifier": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "media": {
      "items": {
        "enum": [
          "Original",
          "Reproduktion"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "owner": {
      "enum": [
        "",
        "Theodor Springmann Stiftung"
      ],
      "index": true,
      "type": "string"
    },
    "public": {
      "index": true,
      "type": "boolean"
    },
    "scans": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "updated": {
      "type": "string"
    },
    "uri": {
      "type": "string"
    }
  },
  "required": [],
  "type": "object",
  "x-index-paths": [
    "media[*]"
  ]
}

=== Simon-Martens/objekte/examples/musenalm/data/items/jp5kerj3ye9zg47.json
{
  "annotation": "Jgg 1824-1831, 1832-1840",
  "condition": "",
  "created": "2026-06-11 10:17:37.569Z",
  "edit_comment": "",
  "edit_state": "Edited",
  "identifier": "404016",
  "location": "105A06",
  "media": [
    "Original"
  ],
  "owner": "Theodor Springmann Stiftung",
  "scans": [],
  "updated": "2026-06-11 10:17:37.569Z",
  "uri": "",
  "public": false,
  "basis": true,
  "editor": ""
}

=== Simon-Martens/objekte/examples/musenalm/data/items/fcryjq9ybwhxw0a.json
{
  "annotation": "§ Standort",
  "condition": "",
  "created": "2026-06-11 10:17:37.650Z",
  "edit_comment": "",
  "edit_state": "Edited",
  "identifier": "404897",
  "location": "105C07",
  "media": [
    "Original"
  ],
  "owner": "Theodor Springmann Stiftung",
  "scans": [],
  "updated": "2026-06-11 10:17:37.650Z",
  "uri": "",
  "public": false,
  "basis": true,
  "editor": ""
}
